### ISSUE TITLE
Problem with invalid token when run in an external environment

### ISSUE THREAD

**Issue by sandeep131** [twilio/twilio-video-app-react#104]
If I run the build in a development environment on the localhost, things run fine.  If I move the environment on AWS instance with a public IP address, the token served is reported as Invalid with an error code of 20101:

If I paste the received token on the jwt.io debugger the decoded item shows a proper header and payload, but says"Invalid Signature".   The token server is off the shelf - same as the one in the repository.

It is also true for the localhost environment (ie it shows the signature to be Invalid).  But the token is accepted in the Dev environment.

Not sure what is going on?  Thx.

**Comment by mbeddall-92** [comment]
I am having the same issue when deploying via HEROKU, if you set HOST in .env this allows the application to load. However, you still get the ACCESS TOKEN issue.

This does not happen in http://localhost:3000 when running "npm start".

**Comment by sandeep131** [comment]
Additionally, even in the localhost environment if you serve the production build, getting the same error - so it seems to be not an issue about the localhost vs some other environment:

ERROR: Invalid Access Token TwilioError: Invalid Access Token
    at t (http://localhost:5000/static/js/2.73bbec9a.chunk.js:2:516328)
    at new t (http://localhost:5000/static/js/2.73bbec9a.chunk.js:2:52176)
    at t.createTwilioError (http://localhost:5000/static/js/2.73bbec9a.chunk.js:2:52060)
    at t.i (http://localhost:5000/static/js/2.73bbec9a.chunk.js:2:663240)
    at t.c.emit (http://localhost:5000/static/js/2.73bbec9a.chunk.js:2:22271)
    at t.value (http://localhost:5000/static/js/2.73bbec9a.chunk.js:2:675083)
    at WebSocket.<anonymous> (http://localhost:5000/static/js/2.73bbec9a.chunk.js:2:673841)

**Comment by timmydoza** [comment]
Hi @sandeep131 - thanks for the information!

Unfortunately, I am unable to reproduce the issue that you are seeing. Locally, I can serve both the development and productions builds, and they both issue valid tokens.  I can also do the same on AWS.  Any additional information you can provide with respect to reproducing the issue would be very helpful.

One idea that I have is to double-check that your `TWILIO_ACCOUNT_SID`, `TWILIO_API_KEY_SID`, and `TWILIO_API_KEY_SID_SECRET` are correct in your `.env` file. If one of these values has a typo, then you would see the issue that you describe.

**Comment by sandeep131** [comment]
When I run the production vs development, the same .env file is being used (TWILIO_ACCOUNT_SID, TWILIO_API_KEY_SID, and TWILIO_API_KEY_SECRET are the same), the token is being served from the same server code, so I am also perplexed as to why this is happening - but it is happening for sure...

**Comment by sandeep131** [comment]
Actually, just realized - When I run the instance in development env: the token server is called...(port 8081)

I have a server instance that prints the call - it shows 
127.0.0.1 - - [24/Mar/2020 19:56:21] "GET /token?identity=Sandeep&roomName=Room1 HTTP/1.1" 200 -

when I try the same with the production build with "serve -s build" - my token server is not being called.  Is there a different endpoint being used in the production?  

What am I missing?

**Comment by timmydoza** [comment]
There's a server that comes with the app (https://github.com/twilio/twilio-video-app-react/blob/master/server.js). It is configured to 1) serve static assets from the `./build` directory, and 2) dispense tokens from the `/token` endpoint. Once you build your assets with `npm run build`, you can run the server with `node server.js`. Can you try this server and let me know if it works for you?

I see what is happening with `serve -s build`.  `serve` is configured to return `index.html` when it receives a request that doesn't correspond with a local asset. This means that when the browser makes a request to `/token`, it receives the contents of `index.html` instead of a valid token. 

If you'd like to use a token server that is running on another host, you'll have to specify the URL of the token server by adding this setting in your `.env` file.

`REACT_APP_TOKEN_ENDPOINT=https://my-token-server.com/token`

Then you'll have to rebuild the app so that this value is consumed: `npm run build`.

**Comment by mbeddall-92** [comment]
timmydoza have you deployed this service? 

I have spent two days debugging this issue, I think it is a genuine bug. See below regarding Twilio support. 

> Hi Michael,
> 
> It looks like this is a common issue. I can reproduce the same in my dev environment. And some user has also reported the issue in GitHub repo: https://github.com/twilio/twilio-video-app-react/issues/104. I'm checking with our engineering team. I hope I can get back to you soon.
> 
> BTW, your JWT token is valid. If I put your API secret in the 'Verify Signature' section, it shows the token is valid. I think the issue is somewhere else. When running in production mode, after clicking the 'Join Room' button, the app tries to fetch a token from localhost:5000/token?identity=TestName&roomName=TestRoom. However, I see the response is not a valid token, but an error message saying "You need to enable JavaScript to run this app."
> 
> 
> Regards,
> Lawrence Qin
> Twilio Support

I have as you can guess come into the same issue, on a newly updated (previously released) production server (deployed live).

**Comment by mbeddall-92** [comment]
`REACT_APP_TOKEN_ENDPOINT=https://my-token-server.com/token `
should not need to be set as he is running the build on the same server. 

If I have read the question, he has no issues on the development (bar the access token not being valid --- which it would be, so I reckon maybe you are not verifying correctly in jwt.io.

However, when it runs in PROD, the token is not being generated. 

This all being said, I am going to set the above in my .env, and going to change the fallback (404) from index.html to random.html and see where I go from there. While still waiting for Twilio to update me via support.

**Comment by timmydoza** [comment]
Hi @mbeddall-92! Sorry to hear that you are having trouble. I hope I can help you get this sorted out. 🙂 

Try running `node server.js` instead of `serve -g build`. 

The server that ship with the app (`server.js`) will serve all static assets, but it will also serve video access tokens from `/token`. Hopefully this does the trick!

When `serve -g build` is run, it only serves static assets. It does not serve tokens from `/token`, which explains why the app isn't working for you.

I realize that after you run `npm run build`, instructions are printed to the console which direct you to run `serve -g build`. I apologize, because these instructions are incorrect. We will get these incorrect instructions removed ASAP.

Let me know how this works for you, and thanks for getting in touch!

**Comment by sandeep131** [comment]
OK, it makes somewhat sense - but I am still confused a bit (new to React env), I do run server.js in both cases below:

1. When I run in development mode - it is npm start -> which runs "concurrently" the server and dev environment: via
  "scripts": {
    "start": "concurrently npm:server npm:dev",
    "dev": "react-scripts start",
    ....
   }
   start the app via "https://domain.com:3000"

2. When running in the "production", I do "node server.js &" followed by "serve -s build"
    and start the app via "https://domain.com:5000"

So I guess, how to start the app in a production environment (or does it matter?)

Thanks for the assistance!

**Comment by sandeep131** [comment]
I think I figured out - didn't see the line in server.js that serves up the build/index.html at the root level:

app.get('*', (_, res) => res.sendFile(path.join(__dirname, 'build/index.html')));

Thanks!

**Comment by timmydoza** [comment]
@sandeep131 Correct.

You just need to run `node server.js` (after you build the app).  Because `server.js` takes care of serving static assets from `./build`, you don't need to run `serve -g build`.
