### ISSUE TITLE
LocalVideoTrack.isStarted() and .isStopped() are true simultaneously

### ISSUE THREAD

**Issue by paulbrie** [twilio/twilio-video-app-react#133]
**Describe the bug**
LocalVideoTrack.isStarted() and .isStopped() are false of true simultaneously

**To Reproduce**
1. Go to: https://codesandbox.io/s/elastic-galois-tsspi?file=/pages/index.tsx
2. Hit the stop button
3. check the console

**Expected behavior**
I expect the localVideoTrack to be started or stopped, but not both 

**Environment (please complete the following information):**
 - OS: MacOS Catalina, 
 - Chrome 80.0.3987.163 (Build officiel) (64 bits)
 - SDK Version: 2.3.0

**Comment by timmydoza** [comment]
Thanks for the issue @paulbrie!

it looks like this relates to the `twilio-video.js` library, and not with this `twilio-video-app-react` application. I would transfer this issue to the `twilio-video.js` repo, but I see that you created the same issue there, so I'll just close this issue here instead.
