### ISSUE TITLE
Reset Passcode to new passcode after room ends so passcodes are never the same.

### ISSUE THREAD

**Issue by spalmertwilio** [twilio/twilio-video-app-react#137]
Support Request Number 4124551

> I am successfully able to deploy the App using instructions in link.
> 
> What I want to change in the functionality to generate the new passcode (probably from client side) while generating new room and share the complete link via sms to participants to join in the video chat.
> 
> I can see that, application is getting deployed along with the generated passcode, which will expire in a week. How can I change this functionality to make it more dynamic and let the passcode expire after every video room has completed?

**Comment by timmydoza** [comment]
Thanks for the suggestion @spalmertwilio!

I've discussed this request with the team.  We like the idea, and it's possible to do, but there are some snags. 

This idea would work well if there was only one room at a time. But because there can be many rooms at a time, it doesn't work so well.  Say Room A is created, then Room B is created, then Room A completes and a new passcode is created.  This means that there is a now a different passcode for users that have yet to join Room B, and they will be locked out. 

Additionally, we only want users to use Twilio Functions to quickly get started with this app. We didn't intend for users to use these Functions in an indefinite manner (which is why they expire after one week). Users may fork these repositories to change the Function expiry, but they do so at their own risk. It isn't something that we would want to add to the Twilio repositories. 

Given all that, we decided to pass on this feature. Thanks again for the suggestion, and please feel free to reach out on slack if you want to chat about it. Thanks!
