### ISSUE TITLE
Safari No Local Video feed and black (or no) video feed on remote browser

### ISSUE THREAD

**Issue by edgolub** [twilio/twilio-video-app-react#147]
I was using the [Twillio video react app](https://github.com/twilio/twilio-video-app-react) for comparing it against my own code, and found the same issue as in my app. 

**Expected behavior:**
Well, it should connect two parties and show the video and audio feed on both sides.

**Actual behavior:**
When connecting via an iPhone (tested with latest version of Safari), there doesn't seem to be any local video feed, and, while I do get both a audio and video track on my remote device, the audio track is fine, while the video track reproduces as just a black video element.

No issues in log on my remote device. I don't own an iPhone myself so can't post a log. The same issue was seen in two different iPhones with the same Safari version though.

The issue does not happen on any Android device.
**Software versions:**

 - [x] Browser(s): Safari 13.1
 - [x] Operating System: iOS 13.4
 - [x] twilio-video.js: 2.3.0
 - [x] Third-party libraries (e.g., Angular, React, etc.): VueJs

**Comment by nclarx** [comment]
I seem to have a similar issue with Safari on iOS - when I plug my iPhone in and get the console output I get:

`Error: getUserMedia is not supported` when I try to initialise the video and audio tracks which is strange given the README says iOS Safari is supported.

I have the same specifications in terms of the iPhone and versions of Safari and iOS used.

**Comment by edgolub** [comment]
I seem to have solved it. It looks like Safari now needs the resolution to be specified.

When calling createLocalTrack try setting these options: 
`{audio: true, video: {frameRate: 24, width: 720, height: 1440}}`

**Comment by timmydoza** [comment]
@nclarx for your issue, could you please check and make sure that your application is being served over a secure context (such as HTTPS).  `getUserMedia` cannot be used in insecure contexts: https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia#Privacy_and_security

If you are using your phone to access a development version of the app (that is run with with `npm start`), you'll have to enable HTTPS in create-react-app with this command: `HTTPS=true npm start`.  When you access the site in your browser you will see a privacy warning (because of the self-signed HTTPS certificate), but you can bypass it. Alternatively [ngrok](https://ngrok.com/) can be a useful tool in this situation (you won't need `HTTPS=true` when using ngrok). Let me know if this doesn't help.

@edgolub Glad to hear that you already solved the issue! If you're still curious, there is some good discussion about a similar issue in the twilio-video.js repo:

https://github.com/twilio/twilio-video.js/issues/927

**Comment by nclarx** [comment]
Thanks @timmydoza I am serving only on http at the moment, that's likely the issue! And thanks @edgolub - i'll bear in mind your solution! :)

**Comment by timmydoza** [comment]
Glad to help @nclarx!

Closing this issue since it seems to be resolved. For @edgolub's issue, we are tracking the problem in an issue (see link in my last comment) on our twilio-video.js SDK repository.

**Comment by nicklyra** [comment]
FWIW, @edgolub's solution also worked for us; specifying the width and the height seems to take care of it for Safari.  At some point we also want to try specifying height and aspectratio with constraints to see if we can give Safari a little flexibility yet still get it to start media.  It's kind of interesting too that this is a 1:2 aspect ratio, not 9:16 or 3:4.
