### ISSUE TITLE
Any plan for adding chat? 

### ISSUE THREAD

**Issue by RusseII** [twilio/twilio-video-app-react#150]
**What is the feature that you would like to see in the app? Please describe.**
Adding a way to send messages, and preferably rich text like images as well

**Is your feature request related to a problem? Please describe.**
Users can't send simple messages that are useful while in a video call. Like links to an external website page.

**Comment by arthursparks** [comment]
This is already supported via DataTracks.

**Comment by timmydoza** [comment]
Thanks for the feature suggestion @RusseII!

At the moment, we don't have plans to add chat to the application.  It's a good feature though, so I'll keep this ticket open. 

To implement this on your own, you could use our DataTrack API. Here's a tutorial if you're interested in getting started: https://www.twilio.com/docs/video/using-datatrack-api

**Comment by timmydoza** [comment]
After discussing the feature with the team, I've decided to close this feature request. Adding a chat feature isn't on our roadmap.  

The thing that makes this tricky, is that we would need to implement a chat feature across all three of our video applications (this app, our [iOS app](https://github.com/twilio/twilio-video-app-ios), and our [Android app](https://github.com/twilio/twilio-video-app-android)), since they all must work with each other. 

As I mentioned before, our DataTrack API can be used to implement a chat feature, but the DataTrack API does not offer any sort of persistence, so all messages sent over a DataTrack are ephemeral. 

Another tool that can be used to build a chat feature is Twilio's Chat API: https://www.twilio.com/chat
