### ISSUE TITLE
Failed to fetch error when using external token server

### ISSUE THREAD

**Issue by corecomps** [twilio/twilio-video-app-react#164]
**Describe the bug**
When using an  external token server (whether it be the built in server.js or my own) it always returns "Failed to fetch" after clicking join room.  The token server actually receives the request and correctly gets the token from twilio and the token server returns tokens without issue when typing in the url directly.

**To Reproduce**
Just to be safe, open server.js and have it listen on port 8084 by modifying this line:
app.listen(8084, () => console.log('token server running on 8084'));`
Update .env with the following:
REACT_APP_TOKEN_ENDPOINT=http://localhost:8084/token
Run command npm run start
Open web browser (it automatically does) to localhost:3000
type in name and room - hit join room
server message stating token was issued for the room

**Expected behavior**
entry into the room successfully (not the failed to fetch error

**Screenshots**
![image](https://user-images.githubusercontent.com/25101185/79672740-694fb700-819a-11ea-81f0-3f8bc40c66ba.png)

**Environment (please complete the following information):**
 - OS: WIndows 10 Pro (64-it)
 - Browser: Chrome 80
 - App Version: 0.1.0
 - SDK Version: 2.3.0
 - Node.js version: v12.16.2

**Additional context**
Trying to get the basic server.js running first and then I'm planning to build my own which will return only pre authorized tokens based on the name/room.

**Comment by timmydoza** [comment]
Thanks for the issue @corecomps!

When you run `npm start` this app runs a proxy that rotes all API calls sent to `localhost:3000` to your server. This is configured by the "proxy" value in `package.json`, which we have set to use `http://localhost:8081/`. Have you updated `package.json` so that the proxy server uses `http://localhost:8084/`?

Here's the Create React App documentation on the proxy server: https://create-react-app.dev/docs/proxying-api-requests-in-development/

**Comment by corecomps** [comment]
Thanks for the help.  it looks like a CORS error.  After doing some debugging I got it to output this error.  Any ideas?

Access to fetch at 'http://localhost:8090/token?identity=SDFCaSDFdsa&roomName=sdvfsdvcsd' from origin 'https://localhost:44332' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled. [https://localhost:44332/room/sdvfsdvcsd]
Failed to load resource: net::ERR_FAILED [http://localhost:8090/token?identity=SDFCaSDFdsa&roomName=sdvfsdvcsd]

**Comment by timmydoza** [comment]
Thanks for the extra info @corecomps!

One thing to try: when running `npm start`, a proxy server is automatically used for API requests. Therefore it isn't necessary to set the `REACT_APP_TOKEN_ENDPOINT` variable. It looks like the app is trying to access the server directly, instead of going through the proxy. 

Try running `npm start` without setting a value for the `REACT_APP_TOKEN_ENDPOINT` variable.

**Comment by corecomps** [comment]
Well I figured it out and I have the code now pointed at my own custom token server!

The issue was a CORS issues (cross site scripting).  I had to make changes in the server.js file to allow it to feed data back.  The error was obvious once I was able to get a break point in the right spot.  I'm dumb in JS still so the whole nested statements of then e => dffdf. next.  was confusing for me and having it all on one line is nice for experts but I finally figured out how to break it out into single lines and the breakpoint worked great.

FYI, Later I had an issue with an https site calling a HTTP token server.  I didn't bother to put it on https originally since it was internal on our network and I was being cheap with a SSL cert but my break point saved the day again.

I hope this helps others!  I'm happy to post the code I used to bypass the CORS

**Comment by timmydoza** [comment]
Glad it's working for you @corecomps!

**Comment by heySoni** [comment]
Hey @corecomps, 
I ran into similar problem today, and not sure how can I fix it. 
Can you share your fix here? It will be really helpful.
Thanks.

**Comment by corecomps** [comment]
Hey! I'm sorry to say that the code is long since out of my hands @heySoni
