### ISSUE TITLE
Can we get live audio stream during meeting ?

### ISSUE THREAD

**Issue by VishalWaman** [twilio/twilio-video-app-react#166]
**Can we have an streaming API wherein we can live audio stream and _perform real-time _transcription__ ?**

We are looking for a feature to show realtime transcription during a meeting, we have tried out all API and this one feature I am stuck on 

I have noticed we have media stream feature in Programable Voice and we have this to get realtime slaudio stream from Twilio Video ?

**Comment by VishalWaman** [comment]
@paynerc @kwhinnery @andrewryno @Gipetto

**Comment by timmydoza** [comment]
Thanks for the question @VishalWaman!

It may be possible to get a live transcription of a meeting's audio.  However, this is a feature that we will not be implementing in this app because it is not on our product roadmap.

In Twilio's [Phone Call Transcription tutorial](https://www.twilio.com/blog/live-transcribing-phone-calls-using-twilio-media-streams-and-google-speech-text), the speech-to-text functionality is provided by Google's [Speech to Text API](https://cloud.google.com/speech-to-text).  Twilio Media Streams are only used to create a media stream from a phone call, so this functionality would be irrelevant in a video room.

It may be possible to implement this feature by sending a media stream from the browser to Google's speech-to-text API. Please consult Google's speech-to-text documentation for specifics on how to accomplish this.

**Comment by VishalWaman** [comment]
@timmydoza can you please help on sample or place in code when I can get this Local Audio track ?
