### ISSUE TITLE
While deploying: Error code 20003: Authenticate

### ISSUE THREAD

**Issue by ijt** [twilio/twilio-video-app-react#171]
**Describe the bug**
An error occurs while trying to deploy: "Error code 20003 from Twilio: Authenticate."

**To Reproduce**
1. `git clone git@github.com:twilio/twilio-video-app-react.git`
2. `cd twilio-video-app-react/`
3. `npm install`
4. `twilio login`
5. `twilio plugins:install @twilio-labs/plugin-rtc`
6. `npm run deploy:twilio-cli`

**Expected behavior**
I expected it to deploy.

**Screenshots**
<img width="705" alt="Screen Shot 2020-04-20 at 10 48 21 PM" src="https://user-images.githubusercontent.com/15530/79829908-1839f180-8359-11ea-9f85-ca1a7e845efc.png">

<img width="1035" alt="Screen Shot 2020-04-20 at 10 52 12 PM" src="https://user-images.githubusercontent.com/15530/79830119-9bf3de00-8359-11ea-980d-cdfcd078ebbd.png">

**Environment **
 - OS: Mac OS X Mojave
 - Browser: N/A
 - App Version: 9b4e47538545305af03b88aa146839c81c0fdabc
 - SDK Version: 2.0.10
 - Node.js version: 13.11.0

**Comment by timmydoza** [comment]
Thanks for the issue @ijt!

The error you see indicates that there is some kind of problem with the credentials that were provided when you ran `twilio login`. It's possible that the Account SID or Auth Token is invalid or may have been revoked. This error can also arise if an API key is deleted in the Twilio Console. There is a good list of possible causes (and possible solutions) in the URL provided in the error message: https://www.twilio.com/docs/api/errors/20003

Unfortunately, that's all the help that I can provide for this issue, as the problem lies with the usage of the Twilio CLI, and not this video app. I recommend looking at that URL and then trying `twilio login` again.

**Comment by ijt** [comment]
@timmydoza, thanks for your reply. After I solved https://github.com/twilio/twilio-video-app-react/issues/174, this started working as well. Specifically, I fixed my .env file to have the right names for `TWILIO_API_KEY_SID` and `TWILIO_API_KEY_SECRET`.
