### ISSUE TITLE
Camera resource is not release when disable the video. 

### ISSUE THREAD

**Issue by bhargavgoli** [twilio/twilio-video-app-react#172]
**Describe the bug**
After Disabled the video, the camera resource is not releasing.
On my laptop browser the green light on, after we disabled the video.

**To Reproduce**
1. Run the project
2. Click on toggle Video button to disable or enable video.

**Expected behavior**
The camera not be used once disabled the video.

**Comment by timmydoza** [comment]
Thanks for the issue @bhargavgoli!

Could you please provide more information about the problem? It will be easier for us to assist you if you can provide us with more information. Specifically:
  - Which commit of the codebase are you running?
  - What browser and browser version are you using?
  - What OS and OS version are you running?
  - Are there any error messages in the browser console?

One thing that is important to note here is that calling `localVideoTrack.disable()` will not release the camera resource. In order to stop the resource (and turn off the light), `localVideoTrack.stop()` will need to be called.

**Comment by bhargavgoli** [comment]
@timmydoza I got the fix.

Thanks for your quick response.
