### ISSUE TITLE
UI issues on iPhone Safari browser when zooming (pinching) in and back out

### ISSUE THREAD

**Issue by qryptadevops** [twilio/twilio-video-app-react#177]
Whilst in a video call on an iPhone 11 using native Safari browser, if you zoom into the video image to look at some detail and then when you zoom back out again, this completely breaks the UI and it is impossible to get back to the default view.

**Comment by timmydoza** [comment]
Thanks for the issue @qryptadevops!

I've confirmed that that there are issues when zooming in on mobile Safari.  I'll discuss solutions with my team and let you know what we decide to do.

**Comment by qryptadevops** [comment]
Thanks @timmydoza appreciate anything your team can do re. this as it means we can't deploy the solution into our production live app until this issue is fixed.

**Comment by qryptadevops** [comment]
Have you seen how whereby.com do their video in iPhone mobile Safari?

**Comment by timmydoza** [comment]
Hey @qryptadevops. 

So the height of the app's main container is set equal to `window.innerHeight`. There's a resize handler  in `hooks/useHeight.ts` that will update the container's height whenever it changes. It looks like pinch-to-zoom sometimes triggers the `resize` event, and this causes the problems that we see.

I found two options that seem to do the trick. Let me know which one you like best. I'd be happy to add one to the app.

1: Disable pinch-to-zoom

Adding this snippet somewhere in the app (say `src/index.tsx`) will disable pinch-to-zoom. Seems to work fine, and it prevents the layout from breaking.
```
  document.addEventListener('touchmove', function (event) {
    // @ts-ignore
    if (event.scale !== 1) { event.preventDefault(); }
  }, { passive: false });
```

2: Take scale into account.

We can update the `useHeight` hook so that it takes the scale of the viewport (from `window.visualViewport.scale` into account). Just update the `onResize` function to the following:
```
    const onResize = () => {
      // @ts-ignore
      setHeight(window.innerHeight * window.visualViewport?.scale || 1);
    };
```

It seems to work well too, but sometimes it isn't perfectly smooth when zooming in. Also, `visualViewport` is an experimental API, so I added a null check in case the object isn't present. 

Let me know what you think! I'll check out whereby.com in the meantime.

**Comment by qryptadevops** [comment]
Hey @timmydoza thanks again for responding so swiftly on this bug.

So went away and thought about options you presented for fixing this.

I think option 2) will be best for us since we need pinch and zoom for our use case where the video callers need ability to zoom in on the other person's view to check things and make diagnoses.

Let me know once you've made the fix and we can test on our side quite quickly.

Cheers!

**Comment by timmydoza** [comment]
@qryptadevops 

I made the change in this branch here: https://github.com/twilio/twilio-video-app-react/tree/fix-mobile-pinch-to-zoom

Please give it a try and let me know how it works for you. Thanks!

**Comment by timmydoza** [comment]
@qryptadevops I went ahead and merged the change into master. Please let me know how it works out for you!
