### ISSUE TITLE
Implement this app as a reusable react component or framework

### ISSUE THREAD

**Issue by amok** [twilio/twilio-video-app-react#179]
**What is the feature that you would like to see in the app? Please describe.**
I'd like to be able to `import` this app as a react component, customise it and use within my app (as a page/modal/section etc).

**Is your feature request related to a problem? Please describe.**
The aim is to be able develop own solutions without reimplementing or copy-pasting chat-room functionality.

**Describe alternatives you've considered**
1) copy-paste - that hurts
2) add the app as a submodule/dependency - difficult since embedding/io/api-calls/etc have to be set up and customised properly.

**Comment by timmydoza** [comment]
Hey @amok, thanks for the feature request!

We have given this feature some thought as a team. It's something that we are interested in doing, but it may be a few months before we get around to it. 

There is [another github issue](https://github.com/twilio/twilio-video-app-react/issues/155) that requests the same feature, and I go into more depth there (including a hacky workaround). I'll close this issue since it's a duplicate, but I will let my team know that we have multiple users asking for this feature. 

Thanks again!
