### ISSUE TITLE
Video toggle using track.disable()

### ISSUE THREAD

**Issue by gauravshrestha** [twilio/twilio-video-app-react#180]
Is there a reason why track.disable() / enable() is not being called in the useLocalVideoToggle.tsx file?  I see that the disable() and enabled() methods are being called on the useLocalAudioToggle hook, but why not on the useLocalVideoToggle hook?  

Thanks

```
  const toggleVideoEnabled = useCallback(() => {
    if (videoTrack) {
      if (localParticipant) {
        const localTrackPublication = localParticipant.unpublishTrack(videoTrack);
        // TODO: remove when SDK implements this event. See: https://issues.corp.twilio.com/browse/JSDK-2592
        localParticipant.emit('trackUnpublished', localTrackPublication);
      }
      videoTrack.stop();
    } else {
      getLocalVideoTrack().then((track: LocalVideoTrack) => {
        if (localParticipant) {
          localParticipant.publishTrack(track, { priority: 'low' });
        }
      });
    }
  }, [videoTrack, localParticipant, getLocalVideoTrack]);
```

**Comment by timmydoza** [comment]
Hey @gauravshrestha. This is an excellent question!

`track.disable()` effectively pauses a track.  When it is called, the track's associated [MediaSteamTrack](https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamTrack) is still active and the track is still published to the room. `track.enable()/disable()` is also a relatively inexpensive operation - when tracks are enabled or disabled, there is no re-negotiation with Twilio's media servers. 

Users frequently mute and unmute their audio in a room, so we use `track.enable()/disable()` for muting audio as it is simple and inexpensive.

We could use `track.disable()` for video tracks, but it does have one major drawback: `track.disable()` does not turn off the camera, which means that the user's camera light stays on when they turn off their local video. 

When a user toggles their local video, they may do so because they want extra privacy. It could be a little disconcerting for users if their camera light remains on after they toggle their local video off. This is mainly why we stop the associated MediaSteamTrack and unpublish the track. We believe that the camera (and camera light) should be turned off when the user toggles their local video. It may be a more expensive operation (with media negotiation), but we figure that users probably won't be toggling their video as frequently as they toggle their audio. Also, turning off the camera and unpublishing the video track can help to conserve bandwidth and battery (on mobile browsers) for all participants in a room. 

Thanks again for the question!
