### ISSUE TITLE
getUserMedia is not supported while running on local server

### ISSUE THREAD

**Issue by gurusoft13** [twilio/twilio-video-app-react#190]
While runing the app on my local server, I just tried to connect from my other local computer using the local ip address.
For example, http://192.168.0.130:3000/

Unfortunately, I just got error message.

> Unhandled Rejection (Error): getUserMedia is not supported

![image](https://user-images.githubusercontent.com/49583931/80914107-30930e80-8d52-11ea-9a9e-8e7e80f83c00.png)

I can see the associative article from [here](https://www.twilio.com/docs/video/javascript-getting-started#set-up-local-media)
But it doesn't give me the solution.

How can I deal with this issue to run the app smoothly on my local?

**Comment by timmydoza** [comment]
Hey @gurusoft13, thanks for the issue!

`getUserMedia` is only available in secure contexts. Accessing the app via `http://localhost:3000` is considered secure because it's local.  If you want to securely access the app from another device on the network you'll need to enable https.

`HTTPS=true npm start`

You'll see a security warning that you'll have to bypass in order for it to work. Alternatively, you can use a tool like [ngrok](https://ngrok.com/), which will let other users access your local server over https.

**Comment by gurusoft13** [comment]
thanks, it works for me
