### ISSUE TITLE
Feature to show equal sized video tracks inside a Room

### ISSUE THREAD

**Issue by krkrosenbergtech** [twilio/twilio-video-app-react#191]
**What is the feature that you would like to see in the app? Please describe.**
Click a button that rearranges the UI inside a Room and shows video tracks equally sized.

**Is your feature request related to a problem? Please describe.**
No.

**Describe alternatives you've considered**
...

**Additional context**
![image](https://user-images.githubusercontent.com/37480046/80960523-54fdf200-8e09-11ea-9de6-16715bd5e331.png)

**Comment by krkrosenbergtech** [comment]
Hi guys, I really like the project and would love to contribute. Could you give me some starter advice if I want to contribute to this feature?

**Comment by krkrosenbergtech** [comment]
@timmydoza would you be helpful here? 🙂

**Comment by timmydoza** [comment]
Hey @krkrosenbergtech - thanks for the feature request! Sorry it took me so long to get back to you. 

Unfortunately this feature is not on our roadmap. This app is designed to showcase a 'collaboration' use case, and in order to provide a good user experience for this use case, we have set the Bandwidth Profile to [collaboration mode](https://www.twilio.com/docs/video/tutorials/using-bandwidth-profile-api#collaboration-mode). This mode allocates significantly more bandwidth to one participant in particular (usually the dominant speaker), and it would not provide a good user experience when the participant's video tracks are arranged in a grid. 

The Bandwidth Profile settings do have a [grid mode](https://www.twilio.com/docs/video/tutorials/using-bandwidth-profile-api#collaboration-mode), which would work very well when the participant's video tracks are arranged in a grid. However, it isn't currently possible to switch between 'collaboration mode' and 'grid mode' while connected to a room. You would have to disconnect from a room, switch bandwidth modes, and then reconnect to a room.  Because of this, we won't be implementing a grid view feature in the app. 

If it ever becomes possible to switch between the two modes while connected to a room, then we can implement this grid view feature. Until then, this app will have to stay as a 'collaboration' app.

Thanks again for the idea! And please let us know if you have any other questions!!

**Comment by trickpattyFH20** [comment]
> If it ever becomes possible to switch between the two modes while connected to a room, then we can implement this grid view feature. Until then, this app will have to stay as a 'collaboration' app.

Is "switch between the two modes while connected to a room" on the roadmap at all? @timmydoza

**Comment by trickpattyFH20** [comment]
Would it be practical to achieve this feature by using a hardcoded setting for
`bandwidthProfile { mode: collaboration }`
and then even though the "dominant" track would have higher bandwidth, still give users an option to switch between "grid" and "collaboration views?

If that's not something this project will support, would it be practical to implement this in a different project? @timmydoza
