### ISSUE TITLE
ERROR Invalid Access Token issuer/subject  Error Code: 20103

### ISSUE THREAD

**Issue by octopyth** [twilio/twilio-video-app-react#194]
**Describe the bug**
When attempting to join a video room I run into: ERROR Invalid Access Token issuer/subject  Error Code: 20103

![image](https://user-images.githubusercontent.com/640759/81012759-64595b80-8e5a-11ea-9129-40bf51b69154.png)

**To Reproduce**
1. EXPORT TWILIO_ACCOUNT_SID=ACxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx; EXPORT TWILIO_API_KEY_SID=SKxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx; EXPORT TWILIO_API_KEY_SECRET=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
2. cp .env.example .env
3. nano .env
``TWILIO_ACCOUNT_SID=ACxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx``
``TWILIO_API_KEY_SID=SKxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx``
``TWILIO_API_KEY_SECRET=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx``
``REACT_APP_SET_AUTH=passcode``
4. npm run deploy:twilio-cli
5. visit url of video app and observe error in the screenshot
6. If I try ``twilio login`` I run into: `` » Secure credential storage failed to load.``

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04.4 LTS
 - Browser: Chrome 80.0.3987.116
 - App Version: 0.1.0
 - SDK Version: 2.1.0
 - Node.js version: v10.20.1

**Comment by timmydoza** [comment]
Thanks for the issue @octopyth!

The `.env` file isn't used by the `npm run deploy:twilio-cli` command, so you don't need to put anything in it.  

You can still pass environment variables to use the `twilio` CLI in case logging in doesn't work. You'll have to make sure that you are using the correct environment variables. You can read about them in the [Twilio CLI documentation](https://www.twilio.com/docs/twilio-cli/general-usage#option-1-recommended).

Looks like you should export `TWILIO_API_KEY` instead of `TWILIO_API_KEY_SID`
and export `TWILIO_API_SECRET` instead of `TWILIO_API_KEY_SECRET`. 

Try that and let me know how it works for you.

**Comment by octopyth** [comment]
Indeed I have misspelled TWILIO_API_SECRET, and I have managed to deploy as I have also exported TWILIO_AUTH_TOKEN. Now removed TWILIO_AUTH_TOKEN and it works like a charm. Thanks!
