### ISSUE TITLE
How to Disable/Off Video & audio by default at start ?

### ISSUE THREAD

**Issue by bhaveshs12** [twilio/twilio-video-app-react#202]
Please provide simple solution ?

**Comment by timmydoza** [comment]
Thanks for the question @bhaveshs12!

I went ahead and made a demo branch to show you how to. implement this feature. You can see the changes here: https://github.com/twilio/twilio-video-app-react/compare/demo-disable-tracks-on-startup

Note: While I was working on this I found a bug in the `useIsTrackEnabled` hook. I made a [PR](https://github.com/twilio/twilio-video-app-react/pull/210) for that fix, but the fix is also included in the demo branch referenced above.

**Comment by timmydoza** [comment]
Closing this issue as it appears resolved. Please let me know if you have any other questions!

**Comment by bisnurana** [comment]
Hi @timmydoza , I am using the latest version of this repo and the example that you shared above did not help me. Therefore, Could you share how can I achieve the same functionality?

**Comment by timmydoza** [comment]
Hi @bisnurana - thanks for the question!

I have a diff [here](https://github.com/timmydoza/twilio-video-app-react/compare/master...timmydoza:example-disable-video-on-load) that disables audio and video on load.  

Note: it still requests an audio track on load, but it immediately disables the track. It does this so that the track can be enabled again when the user clicks on the Unmute Audio button. Video tracks are handled differently (the Mute Video button publishes and unpublishes them instead of enabling/diabling them), so instead of disabling the video track on load, we simply don't request one (by passing `{video: false}` to `createLocalTracks()`.

**Comment by bisnurana** [comment]
Hi @timmydoza  thanks for your help. The above solution seems to disable audio/video at the start but now it doesn't create local tracks anymore when i enable audio/video later, therefore, the remote users in the room are unable to see/talk with each other.

**Comment by papuruth** [comment]
At starting the mic is disabled but after connecting to a room when I'm trying to unmute the audio is not getting published and remote user cannot hear anything.
