### ISSUE TITLE
Responsive issues in Fireforx Browser

### ISSUE THREAD

**Issue by faiyaz-ergo** [twilio/twilio-video-app-react#248]
On a peer-to-peer video calling session using Firefix latest browser, the other parties main video section is getting zoomed. Can see only head of the other party(screenshot attached). 
This is only happening for the desktop view. When I resize down the browser window like a mobile view it shows perfectly fine.
Also the thumb video is showing fine. 

Steps:
1. Open firefox
2. Join into a peer-to-peer call 
3. Have 2 people in the call
4. See the main other party's main video section,
5. See error

the other party's main video should not be zoomed.

![Capture](https://user-images.githubusercontent.com/44223640/84983294-3c982b80-b15a-11ea-9b82-2ef0cdeed135.PNG)

**Environment (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox 77.0.1 (64-bit)
- twilio: "^3.39.3,
- twilio-video: ^2.3.0
- NodeJS Version: 10.20.1,

**Comment by timmydoza** [comment]
Thanks for the issue report @faiyaz-ergo!

This is indeed a bug. Luckily the fix for it is very simple. The fix was recently merged into the master branch of this repository, and you can see the changes here: https://github.com/twilio/twilio-video-app-react/commit/84db1e064edb1d7d5b11474b6c254608d6f69340#diff-717200dda22ae404649099031266f119

Simply adding `gridTemplateRows: '100%',` to line 12 of `src/components/Room/Room.tsx` should fix the issue for you. 

When finished, the `Container` component inside of `Room.tsx` should look like this:
```
const Container = styled('div')(({ theme }) => ({
  position: 'relative',
  height: '100%',
  display: 'grid',
  gridTemplateColumns: `${theme.sidebarWidth}px 1fr`,
  gridTemplateAreas: '". participantList"',
  gridTemplateRows: '100%',
  [theme.breakpoints.down('xs')]: {
    gridTemplateAreas: '"participantList" "."',
    gridTemplateColumns: `auto`,
    gridTemplateRows: `calc(100% - ${theme.sidebarMobileHeight + 12}px) ${theme.sidebarMobileHeight + 6}px`,
    gridGap: '6px',
  },
}));
```

Please try adding that line of CSS and let me know how it works for you. Thanks!

**Comment by faiyaz-ergo** [comment]
Thanks a lot. That problem seems to be solved now :)

**Comment by RJRahevar** [comment]
same as zooming issue for using Twilio video.js in mvc.net core

below CSS  : 
.videocall-page #myVideo {
    position: fixed;
    top: 0;
    bottom: 0;
    height: 84%;
    Object-fit: cover;
}
