### ISSUE TITLE
Button customization

### ISSUE THREAD

**Issue by faiyaz-ergo** [twilio/twilio-video-app-react#252]
Hi there,
I have been using this tool and it's awesome. 

Have few questions though. 
1. Is it possible to hide buttons for screenshare and replace it with camera-switch button?
2. is it possible to change the colours of the buttons. apply custom colour pallet for the buttons?

Thanks in advance.

**Comment by timmydoza** [comment]
Hi @faiyaz-ergo - thanks for the question, and I'm glad you enjoy the tool!

For question 2 - changing the styles is pretty easy. You can edit the `makeStyles` function to add a line for `color` and a line for `background`. For example:

```
const useStyles = makeStyles((theme: Theme) =>
  createStyles({
    fab: {
      margin: theme.spacing(1),
      color: 'blue',
      background: 'red',
    },
  })
);
```

That change will produce a button that looks like this:
![image](https://user-images.githubusercontent.com/12685223/85894115-5e745c80-b7b1-11ea-9a39-87bf46c12f92.png)

You can see the whole file [here](https://github.com/timmydoza/twilio-video-app-react/blob/e33223bbcf12e2b88c50c6b9ede455f1c4f71201/src/components/Controls/ToggleVideoButton/ToggleVideoButton.tsx).

For question 1 - this is possible to do as well. I made an example branch that implements this change if you want to take a look at it. You can see the diff [here](https://github.com/twilio/twilio-video-app-react/compare/master...timmydoza:example-customize-buttons).  

In that diff, the following changes were made:
 - I removed the `FlipCameraButton` component from the Menu Bar and moved the file to the `src/components/Controls` directory
 - The `FlipCameraButton` component now returns a `Fab` (floating action button) instead of an `IconButton` component. This is so the FlipCameraButton matches the style of the other controls. 
 - I added `margin: theme.spacing(1)` to the `FlipCameraButton`. This helps to match the style of the other buttons. 
 - I removed the `ToggleScreenShareButton` component from the `Controls.tsx` file. 

So with all of that, I moved the FlipCameraButton from the Menu Bar to the Controls component, and changed its style to match the other buttons. The functionality of the button works just the same, and didn't need to be changed. 

That all that's needed! Again feel free to use my branch for reference. Also please let me know if you have any other questions. Thanks!

My branch: https://github.com/twilio/twilio-video-app-react/compare/master...timmydoza:example-customize-buttons
