### ISSUE TITLE
iOS Safari Echo on iPhone Safari

### ISSUE THREAD

**Issue by everbslab** [twilio/twilio-video-app-react#255]
**Describe the bug**
When a participant use iPhone with Safari browser when iPhone's user speaks he hears himself voice with an echo.
Remote side sounds clear with no echo.

**Expected behavior**
Either do not pass the voice of a speaker for iPhone/Safari or pass with no echo

**Environment (please complete the following information):**
 - OS: iOS 13.4.*
 - Browser: Safari
 - App Version: 0.1
 - SDK Version: 2.5.1
 - Node.js version: 12.14.1

**Comment by timmydoza** [comment]
Thanks for the issue @everbslab!

We have not been able to reproduce this issue on our end. We have been doing extensive testing of the app in iOS Safari (in order to address other [iOS Safari issues](https://github.com/twilio/twilio-video.js/issues/941)) and the issue you raise has not been reported in our testing. 

How often does this issue occur for you? If it occurs frequently, could you please provide a detailed list of steps that are required in order to reproduce the issue? The more detail you can provide, the more likely it is that we would be able to reproduce the issue. It would also be helpful if you could provide the Room SID of any rooms where this issue occurs. 

Thanks!

**Comment by everbslab** [comment]
Solved this by passing:

https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackSettings/echoCancellation to true
