### ISSUE TITLE
Safari 13.x is not show video on macos & ios

### ISSUE THREAD

**Issue by quochungphp** [twilio/twilio-video-app-react#266]
Hi guys.
Can you help me?
Safari 13 on MacBook and IOS did not show up remote video.
However, Chrome and Firefox are OK.
How can I fix it or tracking it when safari not show video

**Comment by timmydoza** [comment]
Hi @quochungphp - sorry to hear that you are having trouble with the app!

I cannot reproduce the issue that you describe. I'm happy to help out, but I'm going to need more information about your issue. Specifically, what exact steps do I need to take to reproduce the issue? What do you mean when the video does not show up (is it black, or is it missing altogether)? Are there any errors in the console? What is your environment like?

Can you please create a new issue and use our Bug Report template? Please fill out the template with as much information that you can so that we may better assist you.  Thanks!

**Comment by quochungphp** [comment]
Hi guy.Thanks for your reply.
Yesterday, i fixed it my issue. The camera video is not working fluency on web browser , it depend on user media permission.
I requested user media permission before  join to twilio room and it worked fluency.
Sorry, my Eglish is not good
