### ISSUE TITLE
Flipping the camera results in error in console and no camera flip

### ISSUE THREAD

**Issue by matstc** [twilio/twilio-video-app-react#269]
**Describe the bug**
Tapping the button to flip the camera does nothing.

**To Reproduce**

1. Using code after commit 15627c2, deploy and access app with mobile device.
2. Tap the flip button.
3. Nothing visible happens.

**Expected behavior**

The camera should flip.

**Environment (please complete the following information):**
 - OS: Android 9.0.0
 - Browser: Chrome 83.0

**Additional context**
The flipping of the camera works if I revert commit 15627c2.

Looking at the console, I see the following error message:

```
react-dom.production.min.js:17 Uncaught TypeError: o.restart is not a function
    at FlipCameraButton.tsx:29
    at Object.v (react-dom.production.min.js:15)
    at _ (react-dom.production.min.js:15)
    at react-dom.production.min.js:16
    at S (react-dom.production.min.js:16)
    at P (react-dom.production.min.js:17)
    at C (react-dom.production.min.js:17)
    at j (react-dom.production.min.js:17)
    at On (react-dom.production.min.js:81)
    at ue (react-dom.production.min.js:285)
```

Let me know if you need more information.

**Comment by timmydoza** [comment]
Hi @matstc - thanks for the issue!

The commit that you referenced changed `package.json` to upgrade the twilio-video SDK to version 2.7.0.  `npm install` would have to be run in order to actually install the newer version of the library (which includes the `o.restart` function). Did you run `npm install` to update the dependencies? You can verify the version of twilio-video inside the app itself by looking at the `TwilioVideo.version` variable in the browser console.

**Comment by matstc** [comment]
Thanks @timmydoza. I ran `npm install` and things are indeed working fine.

I'll be closing this. Thank you.
