### ISSUE TITLE
Different Screen Mode (Expanded)

### ISSUE THREAD

**Issue by shunkakinoki** [twilio/twilio-video-app-react#281]
**What is the feature that you would like to see in the app? Please describe.**

Really love the project!!! I love Twilio, can't live without it.

Right now, there is only one "mode" for the video communication, 
meaning participants displayed on the left, and a larger screen on the right.

It would be wonderful if there was a mode that expanded each of the participants equally.

**Comment by timmydoza** [comment]
Thanks for the feature request @shunkakinoki!

We're glad you enjoy the app!!

Unfortunately a grid layout is not on our roadmap. This app is designed to showcase a 'collaboration' use case, and in order to provide a good user experience for this use case, we have set the Bandwidth Profile to [collaboration mode](https://www.twilio.com/docs/video/tutorials/using-bandwidth-profile-api#collaboration-mode). This mode allocates significantly more bandwidth to one participant in particular (usually the dominant speaker), and it would not provide a good user experience when the participant's video tracks are arranged in a grid.

The Bandwidth Profile settings do have a grid mode, which would work very well when the participant's video tracks are arranged in a grid. However, it isn't currently possible to switch between 'collaboration mode' and 'grid mode' while connected to a room. You would have to disconnect from a room, switch bandwidth modes, and then reconnect to a room. Because of this, we won't be implementing a grid view feature in the app.

If it ever becomes possible to switch between the two modes while connected to a room, then we can implement this grid view feature. Until then, this app will have to stay as a 'collaboration' app.

Thanks again for the idea! And please let us know if you have any other questions!!
