### ISSUE TITLE
HOLD Automatically when User get another Call to avoid audio to heard by another person

### ISSUE THREAD

**Issue by helloneeraj** [twilio/twilio-video-app-react#293]
**Describe the bug**
Currently, when user is on a video call and another call comes on his phone (or whatsapp call) from USER X, then User X can hear everything which is going in video call. It is a PRIVACY issue and ideally it could go on HOLD
 
**To Reproduce**
1. Join a VIDEO CALL from mobile web
2. Ask other person to call on your mobile
3. Accept the call 
4. Other person can hear all participants of VIDEO CALL

**Expected behavior**
Video Call can go on HOLD to maintain PRIVACY

**Screenshots**
NA
**Environment (please complete the following information):**
 Mobile Web

**Additional context**
NA

**Comment by timmydoza** [comment]
Thanks for the issue @helloneeraj!

Can you please let me know what mobile device and operating system (including version) that you are using? Once I know what kind of device you are using, I will try to reproduce this issue myself. 

Thanks!

**Comment by helloneeraj** [comment]
I think it is happening on all browsers but let me tell you the one which I surely know
It is happening on RED MI PRO 6 ( Android 9) on the CHROME 84.0.4147.125

Should be easily reproducible 
Thanks a lot

**Comment by timmydoza** [comment]
Thanks for the info @helloneeraj!

I tried to reproduce this issue on my Samsung Galaxy S8 (with Android 9), but I was unable to do so. The other person on the phone call was not able to hear the participants in the room. The audio from the video room came out of the phone's speaker (not the earpiece), but it seems that the phone was able to filter out the sound from its own speaker. Perhaps the issue that you are seeing is device specific. 

What makes this tricky is that there is no JavaScript event that we can look for that informs us when a phone call has been answered. The only event that we can use is `visibilityChange`, which is fired whenever the browser is minimized or maximized.  This event is fired when the user switches to a different app, or if they receive a phone call, and there isn't a way to differentiate between the two. We wouldn't want to put the room audio on hold when the browser is minimized, because this would prevent the user from multitasking while in a room. Say a user wants to continue listening to a video call, but they want to switch to a different app to look something up - we wouldn't want to stop the audio in this case. 

Unfortunately, the only solution that I see for this issue is simply disconnecting from a room before answering a call.
