### ISSUE TITLE
Unable to the join video room without giving any of audio or video access permission or both.

### ISSUE THREAD

**Issue by imbiswajit** [twilio/twilio-video-app-react#302]
Currently I am facing an issue like if I don't give any audio or video permission or both, then I am getting some error.

Is there any way to bypass this permission things and overcome with like if the user gives permission or not, the user can join the video room?

How to work on this scenario?

Please help me on this one. Thanks in advance.

**Comment by timmydoza** [comment]
Thanks for the question @imbiswajit!

The behavior you describe is intentional. You can see [here](https://github.com/twilio/twilio-video-app-react/blob/master/src/components/MenuBar/MenuBar.tsx#L127), the 'Join Room' button is disabled when `isAcquiringLocalTracks` is `true`. We won't let the user join the room while the media permission dialog (provided by the browser) is still pending. 

You can get around this by removing the `isAcquiringLocalTracks` variable from the line I referenced above. However, we don't have a mechanism to publish local media _after_ a user has joined a room. This functionality would have to be built. 

Also, the error that is emitted when you deny media permission to the browser doesn't stop any users from joining the room. You can still join a room after denying permissions. But if you want to suppress the error, you can always remove the `catch()` blocks from the `useLocalTracks.ts` file (although we don't recommend this).
