### ISSUE TITLE
Need to change some styling of component. am trying to move the participant window to right.

### ISSUE THREAD

**Issue by usman733** [twilio/twilio-video-app-react#308]
i have managed my requirement in live styling means by inspecting element and then i go the cloned project from twillio web reactjs codebase and changed the respected class. then i run the command "npm run deploy:twilio-cli" after this i got the url as twillio does and then if i check my changes then its not getting in place means no change. BUT its taking effect on localhost.

**Comment by usamadanish22** [comment]
+1

**Comment by sultan-arshi** [comment]
+1

**Comment by timmydoza** [comment]
Thanks for the question @usman733! 

I wonder if you need to run `npm run deploy:twilio-cli -- --override`. That should override your existing deployment with your changes. Let me know how it works for you.

Also, we have completely redesigned the app and now the list of participants is on the right. Check it out - you may like it!

In order to help out further, I'll need some more information from you. Can you please open a new issue and complete our issue template? When creating a new issue, just click on the "Get Started" button in the "Bug Report" row. Then fill out the prompts and provide as much detail as you can. The more detail you provide, the better I can help. 🙂  Thanks!

![image](https://user-images.githubusercontent.com/12685223/95369192-5a69d780-0894-11eb-8160-c3b2ac5d8398.png)
