### ISSUE TITLE
Can roomType be moved to be a setting on the frontend?

### ISSUE THREAD

**Issue by cfluke-twilio** [twilio/twilio-video-app-react#309]
**What is the feature that you would like to see in the app? Please describe.**
Could roomType be changed from a hardcoded function value, to being a selection item in the settings modal? 

**Is your feature request related to a problem? Please describe.**
Not a problem per se. but for ease of switching between p2p and group rooms, I think a frontend per user setting is more flexible.

**Describe alternatives you've considered**
If this is a valid idea, I can attempt a PR.

**Additional context**
I think offering as a setting makes it easier for a developer compare p2p to groups without redeploying. Maybe add an environment variable to not allow setting?

**Comment by timmydoza** [comment]
Thanks for the question @cfluke-twilio!

Our team discussed this feature request, and we decided that the room type setting should be available to the developer deploying the app (through our CLI plugin), and not the non-developer user using the app. Since many of the end-users of this video app aren't developers (patients, students, family members, etc.) we thought it would be best to not expose this setting in the UI.
