### ISSUE TITLE
Record Twilio video track locally (Web)

### ISSUE THREAD

**Issue by pravishanth** [twilio/twilio-video-app-react#312]
Hi, is there way I can access Twilio video tracks to record and save them on the device while the participants are in the room ?

I am using peer-peer rooms.

could you please advise how could achieve this ?

**Comment by dooley1001** [comment]
Hi Twilio Developer Support here,

We have a small recording bot you could use to achieve something similar to what you are asking. I have included the repo link here for your convenience - https://github.com/twilio/twilio-video.js-recording-bot

I hope this helps :)

**Comment by pravishanth** [comment]
@dooley1001,

Thanks for the repo, it's missing to record part of the video, while the audio appears to be be recorded perfectly. Could you please help!

**Comment by timmydoza** [comment]
Thanks for the question @pravishanth!

Unfortunately, Twilio does not have an officially supported way to record P2P rooms. Looks like the repo that @dooley1001 shared is a little out-of-date. Thanks for creating an issue in that repo!

I'd recommend using small group rooms so that you can use Twilio's room recording functionality. More info here: https://support.twilio.com/hc/en-us/articles/360035005493-Record-a-Video-Room-with-Twilio-Programmable-Video#h_9977f0b3-16b7-426a-92db-bd15572f6877
