### ISSUE TITLE
Microsoft Edge: Promise is not defined

### ISSUE THREAD

**Issue by asyfsaeed** [twilio/twilio-video-app-react#314]
On My Edge Browser, it doesn't show Browser not supported instead show Promise not defined

**Comment by timmydoza** [comment]
Thanks for the issue @asyfsaeed!

In order to help, I'll need more information from you. Can you please open a new issue and complete our issue template? When creating a new issue, just click on the "Get Started" button in the "Bug Report" row. Then fill out the prompts and provide as much detail as you can. Thanks!

![image](https://user-images.githubusercontent.com/12685223/95369192-5a69d780-0894-11eb-8160-c3b2ac5d8398.png)
