### ISSUE TITLE
Android chrome video works on mobile but shows up with diagonal lines on other participants

### ISSUE THREAD

**Issue by dannnnthemannnn** [twilio/twilio-video-app-react#321]
Running on android Chrome Pixel 4. Also can't flip the camera.

Looks like this: 
![image](https://user-images.githubusercontent.com/28745869/94749151-f4330100-0337-11eb-9510-28e20ed744d1.png)

Haven't changed any connectionSettings.

Any thoughts?

**Comment by idelgado** [comment]
I believe this is related to https://github.com/twilio/video-quickstart-android/issues/470

**Comment by charliesantos** [comment]
Hey @dannnnthemannnn , can you try the solution mentioned here and see if it works?
https://github.com/twilio/video-quickstart-android/issues/470#issuecomment-623042880
Basically, use H264 codec if you're running on this device and on android chrome.

**Comment by timmydoza** [comment]
Thank for the question @dannnnthemannnn!

Closing this issue since it's related to this [bug](https://bugs.chromium.org/p/webrtc/issues/detail?id=11337) and not the react app. 

This issue has to do with the Android hardware encoder - it distorts the video when the video's width is not a multiple of 16. 

One possible workaround is to avoid widths that aren't a multiple of 16 when they are scaled down. 720 is divisible by 16, but when the video is scaled down to conserve bandwidth (to 360 or 180), the width is no longer a multiple of 16. 

Try using a capture resolution of 768x1280 on pixel devices. This isn't a 16:9 aspect ratio, but the widths will remain a multiple of 16 as the video scales down (640x384, 320x192). This is also true if the video is in landscape orientation (1280x768). 

Let me know how this works out for you!
