### ISSUE TITLE
Mute and Unmute 

### ISSUE THREAD

**Issue by rajkumar73443** [twilio/twilio-video-app-react#341]
**Describe the bug**

I want to enable functionality of mute/unmute for participate (any one can mute other).   

**To Reproduce**
1. Go to ' login  using passcode  continue   than show meeting join screen   put your name and room name than continue . 
2. Click on join now  than show screen all participate join meeting  

**Expected behavior**
I can mute/unmute any participate join meeting

**Screenshots**
![image](https://user-images.githubusercontent.com/66951064/96966572-aae76300-152b-11eb-9da1-fd974496cb99.png)

**Environment (please complete the following information):**
 - OS: windows 10
 - Browser:  Chrome

**Comment by papuruth** [comment]
The same is required for our use case that a user (call him an admin) is able to mute other remote participants.

**Comment by timmydoza** [comment]
Thanks for the feature request @rajkumar73443 and @papuruth!

There are a couple of ways to implement this feature

Locally:

If you want to adjust the volume of participants locally, you can make changes in the app to adjust the volume attribute for the <audio> elements. See: https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/volume

This technique will only adjust the volume in your video app. It will not change the volume as heard by other participants in the room.

Globally: 

In order to change the volume as heard by all participants in a room, you would have to employ the use of [Data Tracks](https://www.twilio.com/docs/video/using-datatrack-api) to send messages to the other participants in the room that instruct their app to either 1) change the volume of elements, or 2) mute or unmute their local audio track.

Unfortunately, a feature like this is not on our product roadmap, so we will not be adding it to the app. We very much appreciate the suggestion though!!
