### ISSUE TITLE
Passcode behavior

### ISSUE THREAD

**Issue by rajkumar73443** [twilio/twilio-video-app-react#342]
**Describe the bug**
 Passcode will expire every 7 days, Is there  any way to overcome this issue, for that i have deploy new build every  7 days.  

**To Reproduce**
1. Go to  login screen. 
2. Click on  passcode 
3. Show passcode expire 

**Expected behavior**
once I deploy code after that passcode must not  be expire any time . 

**Environment (please complete the following information):**
 - OS: windows 10
 - Browser:  Chrome 80
 - App Version: 0.2.0
 - SDK Version: 2.8.0-beta.1

**Comment by timmydoza** [comment]
Thanks for the question @rajkumar73443!

Unfortunately, we don't have a feature in our CLI plugin that allows you to change the passcode expiration date. We decided to set it to one week for security reasons (the numeric passcode is weak and could be guessed). Also, the quick deploy feature is only meant to be used for demo purposes. 

That said, if you do want to change the expiration date (which we don't advise), that can easily be accomplished. 

We recently updated our CLI plugin (see [CHANGELOG](https://github.com/twilio-labs/plugin-rtc/blob/master/CHANGELOG.md#060)) so that it prints a link to the Functions editor in the Twilio Console. With this editor, you can edit the live token server and change environment variables. It looks like this:

![image](https://user-images.githubusercontent.com/12685223/97039969-88087f00-152a-11eb-9675-1f4dd52ea472.png)

To change the passcode expiry, click on Settings > Environment Variables. Then you can edit the API_PASSCODE_EXPIRY variable, like this:

![image](https://user-images.githubusercontent.com/12685223/97040697-89867700-152b-11eb-85b6-4082048390c6.png)

The API_PASSCODE_EXPIRY is the time that the passcode will expire, represented as the number of milliseconds that have passed since 1-1-1970. Simply change this number to whatever value you want. 

To use this new feature, you'll need to upgrade the our CLI plugin by running `twilio plugins:update`. Then you'll need to redeploy the app. Once the app is redeployed, you'll see the link to the functions editor displayed in the console. 

Let me know if you have any other questions! Hopefully this does the trick.
