### ISSUE TITLE
 How can I run with a specific domain?

### ISSUE THREAD

**Issue by Gpe89** [twilio/twilio-video-app-react#348]
**Question**
How can I make the url that you give me to run the application with a specific domain?

**Comment by timmydoza** [comment]
Thanks for the question @Gpe89!

In order to change the domain name used by our Twilio Serverless deployment - you'll need to download and run our [plugin-rtc](https://github.com/twilio-labs/plugin-rtc) repo locally. There are instructions on how to do this in the [README](https://github.com/twilio-labs/plugin-rtc#install-the-plugin-for-local-development).

Once you have the plugin-rtc repo set up locally, you can change the `APP_NAME` variable in [this file](https://github.com/twilio-labs/plugin-rtc/blob/master/src/constants.js#L1) to whatever you'd like. This is the variable that determines the name of the URL that the app is deployed to.

So if you change `APP_NAME` to `"my-cool-twilio-app"`, then the video app will be deployed to a URL that is like: `https://my-cool-twilio-app-1234-5768-dev.twil.io`.

Hope this helps!
