### ISSUE TITLE
Microphone is not working when plugging a USB headset during a call

### ISSUE THREAD

**Issue by hantonelli** [twilio/twilio-video-app-react#353]
**Describe the bug**
When connecting a USB headset, the headset speakers work but the headset microphone does not.

**To Reproduce**
1. Start a call without connecting a USB headset
2. Connect the USB headset
The headset speaker works, but the headset microphone does not.

**Expected behavior**
1. Start a call without connecting a USB headset
2. Connect the USB headset
The speakers and the microphone of the headphones work.

**Environment (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - App Version: 0.2.1
 - SDK Version: 2.8.0-beta.2
 - Node.js version: v14.1.0

**Comment by timmydoza** [comment]
Thanks for the issue @hantonelli!

I'm not exactly sure why this could be happening, but with some extra info I might be able to find some clues.

I wonder if the USB headset isn't being recognized by the browser when it is connected. When you connect the device, does it show up in the Audio Input dropdown (when you click on "Audio and Video" settings)? If you see the device in the dropdown, does it work when you select it?

Also, if you plug in the device and reload the page, are you able to select the device in the Audio Input dropdown?

**Comment by hantonelli** [comment]
Hi @timmydoza ,

Thanks for the answer and the questions. 

The headset is recognized, because the audio output switches to the headset when plugged (USB) / turned on (Bluetooth).
The issue is that the microphone doesn't switch to the headset when it's plugged.
The audio input options are updated when the headset is plugged (USB) / turned on (Bluetooth).

It's possible to reproduce this also using a bluetooth headset on a windows desktop.

There are 2 cases that I tested:

- If I started the call **with the headset connected**, then turn it off, and then turn it on again, then the headset audio input is selected, but doesn't work. I have to deselect the audio input and then select it again it works.
I espected the headset audio input to work without deselecting and then reselecting it.

- If I start the call **with the headset disconnected**, and then turn it on. The audio output switch to the headset, but the mic are  not switch to the headset.
I espected the headset audio input to be selected, the same way the audio output swithes to the headset.

Additional info:
To run this test we used the code of this repo. I changed the code to the the authentication, nothing else.

**Comment by timmydoza** [comment]
Thanks for the additional information @hantonelli!

Unfortunately I don't think that I'll be able to fix this for you. This app has no logic to change devices when they are plugged in. I believe that the behavior that you describe is Chrome's behavior (or your OS behavior) and not this app's behavior. Let me explain:

When I plug in some Apple earbuds (with mic) into my laptop, I do find that the app starts to use both of them. I can also see this reflected in the app's Audio and Video Settings dialog.

This is what i looks like before I plug in the earbuds:
![image](https://user-images.githubusercontent.com/12685223/100966035-3a980e00-34e9-11eb-85d8-e502ff7950c7.png)

And after:
![image](https://user-images.githubusercontent.com/12685223/100966010-29e79800-34e9-11eb-9b27-ec3f80ae804a.png)

However, the app thinks that the device has not changed. This is because the device ID for both devices is `'default'`. In other words, the app does not change device IDs when a new device is added. What we see here is that only the device label changes. 

What is interesting here, is that I can change the selected device by changing my OS settings:
![sound](https://user-images.githubusercontent.com/12685223/100967200-e3e00380-34eb-11eb-9537-1fa3ab15f0f2.gif)

In this GIF, only the device label is changing. No matter which device is displayed, the selected device ID will always be `'default'`.

My point is, the fact that the device automatically changes when you plug it in is a behavior of your operating system. Your system chooses the `'default'` device, not this app. It sounds like your system is correctly choosing your headset as the `'default'` speaker, but not the `'default'` microphone.

I think the solution here would be to choose the microphone that you want to use - either in your OS settings, or in this app's Audio and Video Settings dialog. It may be the case that your OS has your laptop speakers set as the selected device, even after you plug in your headset. 

Thanks again for the issue! Hopefully this helps.

**Comment by hantonelli** [comment]
Hi @timmydoza,

You are right, if you had the default microphone selected when you plug a headset, if the OS doesn't select the headset's microphone as default, the app will not use the newly connected headset's microphone.

I will try to implement some logic to try to detect when a new microphone is connected, by calculating the difference with the previous device list when the devicechange event is triggered, and try to programatically switch to the new microphone by code.

Thanks for your time, analysis and recommendations.
