### ISSUE TITLE
Control volume of each participents in group video.

### ISSUE THREAD

**Issue by swayaminfotech** [twilio/twilio-video-app-react#358]
**Question**
Is it possible to control volume (increase or decrease) for particular participant in a group?

**Additional context**
I am looking for a way use can control volume of each participants in a group video call/meeting.

**Comment by timmydoza** [comment]
Thanks for the question @swayaminfotech!

If you want to adjust the volume of participants locally, you can make changes in the app to adjust the `volume` attribute for the `<audio>` elements. See: https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/volume

This technique will only adjust the volume in your video app. It will not change the volume as heard by other participants in the room. 

In order to change the volume as heard by all participants in a room, you would have to employ the use of [Data Tracks](https://www.twilio.com/docs/video/using-datatrack-api) to send JSON messages to the other participants in the room that instruct their app to either 1) change the volume of <audio> elements, or 2) mute or unmute their local audio track.

Unfortunately, a feature like this is not on our product roadmap, so we will not be adding it to the app. We very much appreciate the suggestion though!!
