### ISSUE TITLE
Chrome Browser on iOS support

### ISSUE THREAD

**Issue by baj84** [twilio/twilio-video-app-react#364]
Hi, I just noticed that chrome browser on an iphone isn't supported. This is a fairly large chunk of my audience. Is there a way to get it working or a future plan to support it?

Thanks.

**Comment by baj84** [comment]
To follow up - Are all versions of Twilio Video unable to run on Google Chrome iOS? Or just the Go that uses WebRTC?

I managed to display a message informing users to use Safari instead. To enable this you must edit `deviceHooks.tsx` and wrap the navigator.mediaDevices in an if statement, like so:
``` useEffect(() => {
    const getDevices = () => navigator.mediaDevices.enumerateDevices().then(devices => setDevices(devices));
    if (navigator && navigator.mediaDevices) {
      navigator.mediaDevices.addEventListener('devicechange', getDevices);
      getDevices();
    }

    return () => {
      if (navigator && navigator.mediaDevices) {
        navigator.mediaDevices.removeEventListener('devicechange', getDevices);
      }
    };
  }, []);
```

I then added some basic functions to check for iOS and tablets in `UnsupportedBrowserWarning.tsx` - 
```
function isChromeIOS() {
  if (/CriOS/i.test(navigator.userAgent) && /iphone|ipod|ipad/i.test(navigator.userAgent)) {
    return true;
  } else {
    return false;
  }
}

function isMobileTablet() {
  const toMatch = [/Android/i, /webOS/i, /iPhone/i, /iPad/i, /iPod/i, /BlackBerry/i, /Windows Phone/i];

  return toMatch.some(toMatchItem => {
    return navigator.userAgent.match(toMatchItem);
  });
}
```

In the render function...
```
{isMobileTablet() && !isChromeIOS() ? (
  <div>
    Unfortunately this browser is not supported. <strong>Please open this link in Safari.</strong>
  </div>
) : (
  ''
)}
```

**Comment by timmydoza** [comment]
Thanks for the question @baj84!

>Are all versions of Twilio Video unable to run on Google Chrome iOS? Or just the Go that uses WebRTC?

All versions.

The reason that twilio-video does not work on iOS Chrome or iOS Firefox is that those browsers are unable to access the phone's camera and microphone. Until these browsers are able to access local media devices, we will not be able to support them. I think your idea of displaying a "Please use Safari" message to the user is a good one.

It appears that iOS Chrome and Firefox may soon be able to access local media devices. There are reports [here](https://bugs.webkit.org/show_bug.cgi?id=208667) that some users are able to get some WebRTC apps working in Chrome and Firefox in version 14.3 os iOS (currently in beta). We will be keeping an eye on this, but at this time I can't say if or when we will support these browsers (because we don't know when iOS 14.3 will be released, and we would also have to perform a full suite of tests).

**Comment by ddc-corporate** [comment]
Not sure what this app is but I can say that looking at this in June 2021 this still seems to be an issue. Somehow, though, Scandit's [SDK](https://www.npmjs.com/package/scandit-sdk) seems to have figured something out. Not sure what the license situation on that is like since I don't speak lawyer and don't know how to interpret it, but the "getCameras" function seems to work without an account / license key, so....
