### ISSUE TITLE
Audio jitter on live view, but not on recording - IOS

### ISSUE THREAD

**Issue by thsorensennrk** [twilio/twilio-video-app-react#372]
**Describe the bug**
When join a conversation with the lastet IOS version (14.2), on the latest iPhone SE, the audio on other participants jitters extremely live in the beginning, and sometimes for a longer period.
See the attached video error_on_iphone.mov in this Dropbox folder for user experience on the iPhone: https://www.dropbox.com/sh/036a7je2f29qy2o/AACs4TBQsyJMV6Dqo7u02BfVa?dl=0

Recording was enabled on the Twilio server, this is also in the Dropbox folder, merged as tw_audio_video_combined.mp4.
The error is not on this file.

When using an older version on IOS, the error does not occur (iPhone X, 13.7), the live conversation sounds perfect.

**To Reproduce**
Run this code, and use a iPhone with the latest version of IOS.

**Expected behavior**
The audio should jitter extremely.

**Screenshots**
Videos available here: https://www.dropbox.com/sh/036a7je2f29qy2o/AACs4TBQsyJMV6Dqo7u02BfVa?dl=0

**Environment (please complete the following information):**
 - OS: IOS 14.2
 - Browser: Safari
 - App Version: 0.2.1
 - SDK Version: 2.8.0 beta 2

**Comment by timmydoza** [comment]
Thanks for the detailed issue @thsorensennrk!

I suspect that you are running into a known audio bug that was introduced in iOS Safari 14.2. You can see the WebKit bug report here: https://bugs.webkit.org/show_bug.cgi?id=218762

Based on the traffic in that ticket, it looks like this bug is impacting many users. Unfortunately, it appears that there is no good workaround for the issue. It seems that we may have to wait until a fix is released in the next version of iOS. I've added myself to the CC list in the but ticket so I can be notified of any updates.

I'll leave this issue open so that other users can easily find it. Thanks again!

**Comment by timmydoza** [comment]
Hey @thsorensennrk!

This week, Apple released iOS 14.3, which should contain a fix to the bug you reported. 🎉 

Please let me know if you continue to experience issues after upgrading to the new version. Thanks!
