### ISSUE TITLE
How to create a private group video session 

### ISSUE THREAD

**Issue by chrnndz3** [twilio/twilio-video-app-react#378]
I would like to create a private video chat or private audio video chat with someone/others while still watching the main screen (dominate indicator). I'm working off of the feature branch called `feature/snack-chat`. 

I don't have any idea on how to do this. Can someone help? Any help will be greatly appreciated.

**Comment by timmydoza** [comment]
Thanks for the feature suggestion @chrnndz3!

This sounds like a neat idea, but I'm afraid that it would be a very complicated feature to implement. I think that in order to establish a private audio or video chat with someone else (while still watching the main screen), you would have to join a second video room with the person that you would like to talk to (while still connected to the main room). Unfortunately, this video app is not equipped to handle connecting to more than room at once (but it is something that is possible to do with out twilio-video SDK). Thanks again for the suggestion, but this feature will not be added to this app as it is not on our roadmap.
