### ISSUE TITLE
Can we Block Video Screen Some Time 

### ISSUE THREAD

**Issue by Gausul** [twilio/twilio-video-app-react#398]
We want to use Audio Feature only Sometimes can you guide me on how we can implement this.

**Comment by timmydoza** [comment]
Hey @Gausul - thanks for the question!

It's pretty easy to make this an 'audio only' app, although it is not designed to be used as such. But if you want to do it, here are some things to try:

First, you can configure the app so that it only requests to capture media from the user's microphone (and not their camera). On [line 66 of useLocalTracks.tsx](https://github.com/twilio/twilio-video-app-react/blob/master/src/components/VideoProvider/useLocalTracks/useLocalTracks.ts#L66), simply pass `false` as the `video` parameter, like this:

```
    const localTrackConstraints = {
      video: false,
      audio: hasSelectedAudioDevice ? { deviceId: { exact: selectedAudioDeviceId! } } : hasAudio,
    };
 ```
 
 This means that a users camera will not be used when the app is started. 
 
 Then, you can comment out the following lines of code in order to hide all buttons related to starting/stopping your camera, and the camera selection menu:
 
 https://github.com/twilio/twilio-video-app-react/blob/5d9d28cef9d930acf2f7321145fcfa32bc14ed73/src/components/PreJoinScreens/DeviceSelectionScreen/DeviceSelectionScreen.tsx#L83
https://github.com/twilio/twilio-video-app-react/blob/5d9d28cef9d930acf2f7321145fcfa32bc14ed73/src/components/PreJoinScreens/DeviceSelectionScreen/DeviceSelectionScreen.tsx#L93
https://github.com/twilio/twilio-video-app-react/blob/5d9d28cef9d930acf2f7321145fcfa32bc14ed73/src/components/MenuBar/MenuBar.tsx#L90
https://github.com/twilio/twilio-video-app-react/blob/5d9d28cef9d930acf2f7321145fcfa32bc14ed73/src/components/DeviceSelectionDialog/DeviceSelectionDialog.tsx#L57-L63

There might be some more things to remove, but I think you get the idea. Good luck!
