### ISSUE TITLE
Handlers calling multiple times

### ISSUE THREAD

**Issue by rachnaban** [twilio/twilio-video-app-react#399]
**Question**
I have noticed that almost all event handlers on room object are getting called multiple times in this repo. 

**Additional context**
 I put console logs in participantConnected, participantDisconnected, dominantSpeakerChanged, networkLevelChanged, etc. 
 Like when a new participant joins the room , "participantConnected" event is getting fired 3 times.
Also, handleDominantSpeakerChanged is getting called 5 times whenever the other participant is unmuting audio . Similarly when muting back, its calling for 5 more times with null value.

I need your help in understanding the reason behind these multiple calls.

**Comment by timmydoza** [comment]
Hi @rachnaban - thanks for the question. I think this is an interesting topic! 

Looking at the `participantConnected` handler - if I put a `console.log('participantConnected')` inside the handler, I also see that the message is logged three times in the console. This is not because the `participantConnected` event fires three times. It is because the `participantConnected` event has three event handlers attached to it (and the event is only fired once).

But why does it have three handlers attached to it?

A good question! This has to do with how these hooks (like `useParticipants`) work. A hook like `useParticipants` will be called by every component that uses it. If three different components use it, then it will be called three times, and it will attach three different event handlers as a result.

We can see this if we inspect the `twilioRoom` object in the browser console.  The `twilioRoom` object inherits from the [EventEmitter](https://nodejs.org/api/events.html#events_class_eventemitter) class from Node, and this class has some internal properties that we can take a look at. `twilioRoom._events` is an object where each key is an event name, and each value is an array of listeners. So if we look at `twilioRoom._events.participantConnected`, we can see all of the listeners associated with that event:

![image](https://user-images.githubusercontent.com/12685223/106683555-f2957600-6581-11eb-8515-a17af5f212a3.png)

We can even look at each listener to see that the `[[FunctionLocation]]` of each listener comes from `useParticipants.tsx`. These three handlers correspond to to different React components in this application. So when the first listener is called, component A will be updated, when the second listener is called, component B will be updated, and so forth.

Many of the hooks inside the `src/hooks` folder attach event handlers to the `room` object (or other objects from the twilio-video SDK). If multiple components use the same hook, then there will be multiple listeners attached (one for each component). 

The EventEmitter class from Node has a built-in protection mechanism so that this pattern doesn't get out of hand. A handful of listeners attached to an eventEmitter is no problem, but something like 50 listeners attached to an eventEmitter would be a problem (and it probably means that there is a bug somewhere). Luckily for us, if we add many listeners to an eventEmitter, we will see a warning like this:

![image](https://user-images.githubusercontent.com/12685223/106684947-a8fa5a80-6584-11eb-8d8d-1993e18d43f0.png)

This doesn't mean that anything is necessarily wrong. It's just the EventEmitter class telling us that quite a few listeners have been attached, and that we should look into things. If we are sure that this is correct, we can change the threshold of the warning with `twilioRoom.setMaxListeners(20)`, to increase the threshold to 20 (for instance). As I work on this app, I make sure that this warning doesn't pop up. 

I hope this answers your question! Please let me know if you have any additional questions. I think this is a pretty interesting topic, so I'm happy to explore it further. 

Happy coding!

**Comment by rachnaban** [comment]
Thanks @timmydoza for showing me the LIGHT here!! This screen shot of window.twilioRoom is extremely helpful to me.
As I understand I need to do some homework on Node EventEmitter to understand this more clearly. I will do that for sure.
For now, I am good on this and so closing this question, will open a new one in case I got stuck.

I really appreciate your patience in explaining this to me. Thanks.
