### ISSUE TITLE
FireFox freeze video tracks if share screen with low bandwidth

### ISSUE THREAD

**Issue by alex-konoval** [twilio/twilio-video-app-react#406]
**Describe the bug**
If a user starts sharing a screen on Firefox with low bandwidth his video track and screen track are frozen for other participants.
If a Chrome user shares his screen with the same bandwidth images become a bit laggy, but both are shown.

**To Reproduce**
1. Limit your internet speed with download 1.5Mb and upload 0.5Mb.
2. Run the `twilio-video-app-react` locally.
3. Join the same room from Chrome and Firefox.
4. Start screen sharing from Firefox.
5. For Chrome user video stream is frozen, screen stream is black.

**Expected behavior**
The same as if a Chrome user sharing a screen, I expect to see streams, even a bit laggy.

**Screenshots**
<img width="1319" alt="Screen Shot 2021-01-25 at 3 28 46 PM" src="https://user-images.githubusercontent.com/8490547/105712140-16254480-5f22-11eb-8d25-0550698418c4.png">

**Environment (please complete the following information):**
 - OS: macOS Catalina Version 10.15.7
 - Browser: **Chrome** Version 88.0.4324.96 (Official Build) (x86_64), and **Firefox** 84.0.2 (64-bit)
 - App Version: 0.2.1
 - SDK Version: 2.9.0
 - Node.js version: v12.19.0

**Additional context**
I think it could be related to `trackSwitchOffMode`, something like both video tracks is switched off.
Note: there are no console errors in both browsers.

**Comment by timmydoza** [comment]
Hey @alex-konoval - thanks for the issue!

Couple of quick questions first:

- Do you have a room SID that you can provide for a room where you experienced this issue? The room SID can be found in the browser console as `window.twilioRoom.sid`. If you send us a room SID, we can take a look at the logs. 

- Did you join a room in Chrome and Firefox from the same computer? Or did you join from Chrome on one computer and from Firefox from a different computer? 

I think I have an idea of what is going on, but I'm curious about this information. Let me know about the above and I'll get back to soon. 

Thanks!

**Comment by alex-konoval** [comment]
Hey @timmydoza.
Answering your questions:
- here is example room sid: `RMea228151189cb9995b0fbeeadbcff978` and `RM95fd3eeacc9736dffd730da21ec827b8`. Please let me know if you need more examples.
- I used a single device.
Please let me know if you need any other information.
And thank you for looking into this.

**Comment by timmydoza** [comment]
Hey @alex-konoval - thanks for the info!

I was able to reproduce these results when I limited my network connection in the way that you described (1.5mbps down and 0.5mbps up). I don't think that throttling the network down to such speeds is a realistic way to simulate poor network conditions. 

Since both browsers are running on one computer, this means that the two instances of the app have to share the limited upload bandwidth of 500kbps. This means that each app gets approximately 250kbps upload, which is quite low. 

I performed this test with the two browsers running on two different computers, and the results we better, but still not great. 

However, there are still some ways to improve the performance of this app if you are anticipating that some of your users may experience poor network conditions. 

I have been talking to the account manager that has been working with your account, and I have a better idea of what your use case is. For a use case that only has two participants in a room, with no requirement to record the room, there are some easy things that can be done to improve performance:

- Use Peer to peer rooms instead of group rooms. 

With p2p rooms, media does not need to be sent to Twilio's Video Media Servers. Instead it can be sent directly from one participant to another. This can improve performance, as the upper limit of available bandwidth is determined by the participant's internet connections, and not our media servers. Plus, the media in peer-to-peer rooms in encrypted end-to-end, which can be a plus.

- Disable VP8 simulcast

Simulcast isn't needed in rooms with only two participants (plus it isn't supported in P2P rooms). Simulcast involves the simultaneous sending of different versions of the same video track encoded independently at different resolutions and framerates. This can improve the experience for remote participants in rooms with more than three people, but it does require additional bandwidth because more data would have to be sent. Disabling it in your application will conserve bandwidth. 

Disabling simulcast can be achieved by using this option:
`preferredVideoCodecs: [{ codec: 'VP8', simulcast: false }]`

on this line: https://github.com/twilio/twilio-video-app-react/blob/master/src/utils/useConnectionOptions/useConnectionOptions.ts#L38

Please try these techniques and let me know how they work out for you! If you are still seeing issues, there may still be more thing that can be tried, but I think these should yield some good results.

**Comment by alex-konoval** [comment]
Thank you, @timmydoza.
We are testing your suggestions and looks like it has some positive effect. Once we have some final results I'll let you know.

> there may still be more thing that can be tried

If you have some more thoughts/ideas on this I'd appreciate hearing them.

**Comment by timmydoza** [comment]
Hey @alex-konoval!

Sure! I have a couple other ideas about reducing bandwidth usage if you're interested. I normally wouldn't recommend these ideas because this app seems to function pretty well under most network conditions. But if you are finding that some of your customers have poor network conditions, then it may be worth it to make this app less demanding on their systems.

These recommendations will reduce bandwidth consumption at the cost of video quality. 

First, in this app, we already reduce the max subscription bitrate on mobile devices only. You can see it in the settings [here](https://github.com/twilio/twilio-video-app-react/blob/master/src/utils/useConnectionOptions/useConnectionOptions.ts#L43). One idea is to change this file so that the `maxSubscriptionBitrate` is set to `2500000` on all devices, not just mobile devices. You could even play with reducing this number further if you wanted. 

Another idea is to reduce the size of the video that is sent to other participants. This can be changed in [this file](https://github.com/twilio/twilio-video-app-react/blob/master/src/constants.ts#L2-L3). Instead of using 720p video, you could try qHD (Quarter High Definition) - aka 540p (width: 960, height: 540). This would reduce how much data is uploaded, which would make the app function better in cases where upload bandwidth is limited. 

Lastly, if screensharing is used in your app, those settings can be modified [here](https://github.com/twilio/twilio-video-app-react/blob/master/src/components/VideoProvider/useScreenShareToggle/useScreenShareToggle.tsx#L20-L22).  The framerate for screen sharing can be surprisingly low. Try reducing it to 5 fps and see how that looks. You can also try reducing the resolution if you want. 

These are some ideas to try - you can try just one or you could try all of them. I'm not super familiar with your use case, so I not sure what the best course of action would be here. But if you're noticing that your customers have very slow internet connections, these could be some things to try.

Please let me know if you have any other questions.

**Comment by alex-konoval** [comment]
@timmydoza thank you for sharing your ideas.
I think this issue can be closed.
Thank you!
