### ISSUE TITLE
Detached Remote audio tracks on navigation

### ISSUE THREAD

**Issue by Asif-chohan** [twilio/twilio-video-app-react#424]
I've implemented this code with nextjs. There are two pages (one for Chat and the other for video call). The scenario is that the user can navigate to the chat page while he is connected in a room (without disconnect the room).

When a user in a room and navigate to the chat page, the remote audio is disconnected (local audio works fine). again navigate to the call screen, the remote audio works fine.

I did not find why the audio is detached while navigating to another page. Need to resolve this issue, so that user can freely move through the whole app while connected in a room.

Thanks.

**Comment by timmydoza** [comment]
Thanks for the question @Asif-chohan!

Without seeing your application, my guess would be that the `<audio>` elements for the remote participants are being removed when you navigate to the chat page. Can you check that this is the case? If you have `<audio>` elements on the page, you should be able to see them in the DOM (near the bottom):

![image](https://user-images.githubusercontent.com/12685223/108793507-e711eb00-7540-11eb-88f8-58da2d422cb4.png)

Alternatively, you can use `document.querySelectorAll('audio')` to find any audio elements that are on the page.

If the `<audio>` elements are being removed from the page when you navigate away, then a different approach may be needed.

Instead of navigating to another page, what if you rendered both pages at the same time, but changed their visibility so that only one 'page' was visible at a time? This way all of the `<audio>` elements should stay on the page, and you would be able to hear everyone.

Here's a simple demo of what I mean: https://codesandbox.io/s/lively-mountain-0zuoz?file=/src/App.tsx

Let me know if that helps! If you are still seeing the issue, is there any way that you could send over some demo code for me to look at?

**Comment by Asif-chohan** [comment]
Hi @timmydoza ,

Thanks for the reply. The problem is exactly the same as you describe. However, I fixed that by calling `<ParticipantStrip />` on the Chat page. It resolves the audio as well as video issue. Thanks for your help.

**Comment by timmydoza** [comment]
Glad to hear it's working @Asif-chohan! Please let me know if there's anything that I can help with.
