### ISSUE TITLE
Can't change audio output in FireFox and Safari

### ISSUE THREAD

**Issue by artem-gorokhovskii** [twilio/twilio-video-app-react#427]
We can't change audio output device on FireFox and Safari:
![image](https://user-images.githubusercontent.com/45370857/108495571-021ef980-72ba-11eb-8a6b-c06e59797dbe.png)

I've used command to test in console:
`navigator.mediaDevices.enumerateDevices().then(console.log)`

Safari:
![image](https://user-images.githubusercontent.com/45370857/108495150-7ad18600-72b9-11eb-90b8-702808edc4b5.png)

FireFox:
![image](https://user-images.githubusercontent.com/45370857/108495685-25e23f80-72ba-11eb-80a6-49df94750f01.png)

But we have another situation in Chrome:

Chrome:
![image](https://user-images.githubusercontent.com/45370857/108495790-47432b80-72ba-11eb-9812-dfc088053b10.png)
![image](https://user-images.githubusercontent.com/45370857/108495865-5f1aaf80-72ba-11eb-8bb1-c67691ad5785.png)

Seems that's the problem with browsers, but can we do something with that?

**Expected behavior**
We can choose audio output both in FireFox and Safari (and Chrome)

**Real behavior**
We can't choose audio output in FireFox and Safari.
We can choose audio output in Chrome.

**Environment**:
Browsers: FireFox 85.0.2 (64-bit), Chrome Version 88.0.4324.150 (Official Build) (64-bit), Safari Version 14.0.3 (16610.4.3.1.4)
App Version: 0.2.1
Twilio-video: 2.9.0
Node.js version: 14.15.1

**Comment by timmydoza** [comment]
Thanks for the question @artem-gorokhovskii!

> Seems that's the problem with browsers, but can we do something with that?

Good question! But unfortunately, we can't do anything about it. If you try other browser-based video apps (Jitsi, Google Meet), you'll see that they have the same limitations. 

Additionally, In order to change the output device, we need to call the `setSinkId()` method on `<audio>` elements. This method does not exist in Firefox or Safari, so we are unable to change output devices in those browsers. See the [browser compatibility table](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/setSinkId#browser_compatibility) for that method.
