### ISSUE TITLE
Safari browser doesn't give choice to share screen/applications/tabs

### ISSUE THREAD

**Issue by Viktar-krauchyk** [twilio/twilio-video-app-react#430]
**Describe the bug**
It is impossible to choose what to share in Safari browser (screen/applications/tabs).
Safari share only first screen, It doesn't give ability to chose which screen to share.

**To Reproduce**
1. Open video call in Safari browser
2. Click 'Share screen' button

**Expected behavior**
Overlay is opened with share options:
- One of the screens
- One of the opened applications
- One of the opened tabs in Safari

**Real behavior**
Safari share only first screen by default without asking anything 

**Screenshots**

![safari2](https://user-images.githubusercontent.com/79318949/108524210-d7479c00-72df-11eb-8bb7-4f5d6c9e3f80.gif)

**Environment:**
OS: Windows 10
Browsers: Safari Version 14.0.3 (16610.4.3.1.4)
App Version: 0.2.1
Twilio-video: 2.9.0
Node.js version: 14.15.1

**Comment by timmydoza** [comment]
Thanks for the question @Viktar-krauchyk!

I tried screen sharing in Safari and I can confirm the behavior that you describe. However, the problem here lies with the Safari browser itself, and not with this Twilio Video Application. 

When screensharing with Chrome, you are given the choice to choose other screens or tabs, but this user interface is built into Chrome, and not this application. Unfortunately, there are no changes that we can make to this application in order to change how Safari handles screen sharing.

If you try screen sharing in any other browser-based video app (like Jitsi or Google Meet), you will notice the same thing. 

Thanks again for the question!
