### ISSUE TITLE
Hooks under `VideoProvider` directory is being used outside?

### ISSUE THREAD

**Issue by ardok** [twilio/twilio-video-app-react#450]
**Question**
In `VideoProvider/index.tsx`:
```
/*
 *  The hooks used by the VideoProvider component are different than the hooks found in the 'hooks/' directory. The hooks
 *  in the 'hooks/' directory can be used anywhere in a video application, and they can be used any number of times.
 *  the hooks in the 'VideoProvider/' directory are intended to be used by the VideoProvider component only. Using these hooks
 *  elsewhere in the application may cause problems as these hooks should not be used more than once in an application.
 */

```

We have `useSelectedParticipant()` hook under `VideoProvider` directory, and yet it's being used outside of `VideoProvider` directory, namely `useMainParticipant.tsx` and `ParticipantList.tsx`.

So, can the hooks inside `VideoProvider` directory be used outside of that directory then?

**Additional context**
N/A

**Comment by timmydoza** [comment]
Thanks for the question @ardok!

This is a very good question! So the hooks in the `VideoProvider` directory may not work correctly if they are used outside of the `VideoProvider`. So to answer your question, the hooks in the `VideoProvider` directory cannot be used outside of it. Some of the hooks provide methods and properties that are useful throughout the app, so these methods and properties are exposed through the `useVideoContext()` hook, which can be used anywhere in the app. 

My idea with the `VideoProvider` component was to make it as application-agnostic as possible. Meaning, it could (hopefully) be used in any app without issue. 

There are some properties and values that are specific to this application which need to be used throughout the application. These are found in the `state` directory and they are exposed with the `useAppState()` hook. 

The values contained in the `useSelectedParticipant` hook are specific to this application (not every app would have a feature that lets you select a participant), so I think that it would make sense for this hook to belong in the `state` directory instead of the `VideoProvider` directory. It relates more to the application state than it does video. So it appears that I mistakenly included it in the `VideoProvider` directory. 

I'll look into moving the `useSelectedParticipant` hook into the `state` directory. I think it makes sense for it to be there. This wouldn't change how the app functions, but at least the structure of the app would be consistent with my code comments about the same. 

Thanks for bringing this to my attention - and please let me know if you have any other questions!

**Comment by ardok** [comment]
@timmydoza sounds good!

Thanks for this app. Helps splitting my app into smaller "hooks" instead of what we currently have, just one big giant hook of "useTwilioRoom", which is not ideal.
