### ISSUE TITLE
Choosing a specific layer from Simulcast?

### ISSUE THREAD

**Issue by baj84** [twilio/twilio-video-app-react#456]
When using simulcast for a group chat is it possible for the client to use a specific layer?

Thanks!

**Comment by timmydoza** [comment]
Thanks for the question @baj84!

Unfortunately, there isn't a way to tell the twilio-video SDK choose a specific simulcast layer. 

I'm curious about your use case. Are there any additional details that you can provide? Are you trying to select a specific layer for a participant to publish to a room, or are you trying to select a layer for a participant to subscribe to?

**Comment by baj84** [comment]
Thanks for the reply @timmydoza!

We will have 50 people in the group chat and we want to show the lower quality layer for each participant, so that it helps with the performance of the browser.

**Comment by timmydoza** [comment]
Thanks for the additional information @baj84!

That does sound like a good use case. Still, there isn't a way to have our SDK select a specific simulcast layer. 

The good news it that there are some new features coming down the twilio-video.js pipeline that will make it easier for developers to reduce CPU usage and improve performance in their video apps. These features would do a lot of work behind the scenes, and developers would not have to write much code in order to implement them. Be sure to check out the [resleases](https://github.com/twilio/twilio-video.js/releases) page for the twilio-video SDK every once in a while to look for the announcement of these features. 

In the meantime, please let me know if you have any additional questions!
