### ISSUE TITLE
Screen sharing going in recursive mode

### ISSUE THREAD

**Issue by dhiraj3301** [twilio/twilio-video-app-react#459]
Hi,

When i do screen sharing (by selecting entire screen), It is going in recursive mode, Please refer attached screenshot, Please advice what can be done to fix this issue?

![Recursive screen sharing](https://user-images.githubusercontent.com/11137490/111597530-438cc100-87f4-11eb-8866-6d4fe74b929d.png)

**Comment by timmydoza** [comment]
Hi @dhiraj3301 - thanks for the question!

The effect that you can see in your screenshot happens when a user captures their screen and then displays it in the app. It gets re-captured and re-displayed over and over again in an infinite loop. So to get rid of the recursive effect, we must break the loop somehow. 

We solved this problem in our React app by adding logic so that the user who is sharing their screen will never see their own screen displayed in the app. Instead, the user sharing their screen will simply see a banner that says "You Are Sharing Your Screen" and they see the video of the dominant speaker:

![image](https://user-images.githubusercontent.com/12685223/112076625-5c70db80-8b40-11eb-9af1-2eca2236eb95.png)

On this line of code in the app, we disable screen sharing when the local participant is identical to the screen sharing participant, by passing `false` as the `enableScreenShare` prop: https://github.com/twilio/twilio-video-app-react/blob/master/src/components/MainParticipant/MainParticipant.tsx#L29

To see how the `enableScreenShare` prop is handled, see this line: https://github.com/twilio/twilio-video-app-react/blob/master/src/components/ParticipantTracks/ParticipantTracks.tsx#L33

I hope this helps to clear up the issue for you! Please let me know if you have any additional questions - we're happy to help.
