### ISSUE TITLE
Force specific video size when creating local video track?

### ISSUE THREAD

**Issue by baj84** [twilio/twilio-video-app-react#465]
Hi, i'm trying to force a specific video size when creating the local video track, but none of these seem to have any effect as when I console.log the videoTrack it shows the dimensions of {width: 640, height: 480}.

Is it possible to force a small video resolution?

```
    const videoTrack = await createLocalVideoTrack({
      audio: false,
      video: {
        width: 176,
        heigh: 144,
        frameRate: 24,
        deviceId,
      },
      renderDimensions: {
        low: { height: 144, frameRate: 24, width: 176 },
        medium: { height: 144, frameRate: 24, width: 176 },
        high: { height: 144, frameRate: 24, width: 176 },
      },
      preferredVideoCodecs: [
        { codec: 'H.264', simulcast: false },
      ],
    });
```

**Comment by timmydoza** [comment]
Thanks for the question @baj84!

It is possible to force a smaller video resolution. The first thing that I see is that the options aren't being correctly passed to `createLocalVideoTrack`. The correct usage would look like this:

```
const videoTrack = await createLocalVideoTrack({
  width: 176,
  heigh: 144,
  frameRate: 24,
  deviceId,
});
```

`createLocalVideoTrack` doesn't accept any options for `audio`, `renderDimensions`, or `preferredVideoCodecs`. `renderDimensions` and `preferredVideoCodecs` are options that can be passed to the `Video.connect` function. If you're interested, here are the docs for the options that can be passed to the `connect` function: https://media.twiliocdn.com/sdk/js/video/releases/2.13.0/docs/global.html#ConnectOptions

There's still more that can be done if the above snippet doesn't work out. We can try to force certain dimensions by passing an object instead of a number:

```
const videoTrack = await createLocalVideoTrack({
  width: { exact: 176 },
  heigh: { exact: 144 },
  frameRate: 24,
  deviceId,
});
```

I think that would do the trick for you. There's one thing to watch out for when you use the `exact` keyword. If the video input device does not support the specified dimensions, then you may run into an [OverconstrainedError](https://developer.mozilla.org/en-US/docs/Web/API/OverconstrainedError) when calling `createLocalVideoTrack`. 

If that's the case, it may be best to take an approach that is a little more flexible. If you're interested you could try something like this: 

```
const videoTrack = await createLocalVideoTrack({
  width: { min: 1024, ideal: 1280, max: 1920 },
  height: { min: 576, ideal: 720, max: 1080 },
  frameRate: 24,
  deviceId,
});
```

With the `min`, `max`, and `ideal` keywords, you can specify a certain dimension that should be used, but also a range of dimensions that can be used in case the `ideal` dimension isn't possible. 

The `createLocalVideoTrack` function used [getUserMedia](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia) under the hood, so any options that you can pass to `getUserMedia` (as the `video` property) can be passed to `createLocalVideoTracks`.

Let me know if this works for you, and please let me know if you have any additional questions!
