### ISSUE TITLE
Is there a recommended way to set initial status of audio and video (on / off)?

### ISSUE THREAD

**Issue by ardok** [twilio/twilio-video-app-react#468]
**Question**
Hi, 

Just wondering, is there a way for that?
Sample use case:
* User lands on foo.com, do a video call.
* Before joining a room, user turns off video and audio.
* Store this preference in local storage, that is video and audio off (or store it on the server even, whatever).
* Next time user joins, read their preference, and when acquiring the track, they need to respect that, that is video and audio are disabled for this particular example.

I know that I could just disable it myself after getting it by calling detach or whatever it is. Though wondering whether I could just acquire it and turn it off by passing in some options or something?

**Additional context**
N/A

**Comment by timmydoza** [comment]
Thanks for the question @ardok!

This sounds like a good approach to me. In fact, I think I will be implementing something like this in order to address this github issue: #460

I'm not sure when the fix will land, but it is something that I'd like to add to the app. Stay tuned! I'll update #460 when the fix is in.
