### ISSUE TITLE
Blinking issue

### ISSUE THREAD

**Issue by iakshaypatel** [twilio/twilio-video-app-react#477]
Please check attached video.

https://user-images.githubusercontent.com/79964187/113147243-35a45a80-924e-11eb-858c-1510c71f125b.mp4

**Comment by Vinod1144** [comment]
constantly refreshing the video

**Comment by timmydoza** [comment]
Hi @Vinod1144 - thanks for the question!

I think I have a good guess as to what is happening in your app. The resolution of the video tracks that are received by the Twilio Video SDK can change at any time depending on network conditions. When this happens, you may see that the size of the video track changes as the resolution changes. This is because but its default width and height of a `<video>` element is defined by the video being rendered. I think the fix here is to use CSS to specify a new width and height.

In the twilio-video-app-react we use something as simple as this:

```
video {
  height: 100%;
  width: 100%;
}
``` 

This will tell the `<video>` element to occupy the space of its parent element. Because we are specifying the size of the video element with CSS, it will no longer change size when the track's dimensions change.

Additionally, you may want to try out the `object-fit: cover;` property. This will change how the video is 'stretched' over the video element. This may or may not be desirable depending on your use case, but it could be something to try out.

I hope this solves your issue! Please let me know if you have any additional questions.
