### ISSUE TITLE
chat conversation won't work when we have used token api of .net core

### ISSUE THREAD

**Issue by Vinod1144** [twilio/twilio-video-app-react#484]
Hi,

First of all we have replace your token api to our 3rd party api , i have implemented same code which you did in below url 

https://github.com/twilio-labs/plugin-rtc/blob/master/src/serverless/functions/token.js

I have also attaching the get token api call of .net core api.

I have tried several ways to get the conversation but it throws an error called "There was a problem getting the Conversation associated with this room", i have also attached the screenshot for the same.

i'm creating conversation only 1 time and then after next time i will get conversation and add participants but still getting error from both the function getConversationByUniqueName and getConversationBySid.

![image](https://user-images.githubusercontent.com/59162092/113711999-3aac5280-9703-11eb-8e87-65b3e31ed8a5.png)

![image](https://user-images.githubusercontent.com/59162092/113712711-169d4100-9704-11eb-9e51-c3349d95e02e.png)

![image](https://user-images.githubusercontent.com/59162092/113712144-629bb600-9703-11eb-8147-8175f83bb52e.png)

Please solve this issue asap as we are on live and getting delayed for this issue.

Thanks.

**Comment by Vinod1144** [comment]
can you please fix this asap ?

**Comment by timmydoza** [comment]
Hi @Vinod1144 - sorry to hear you are running into an issue here!

Thanks for sharing your code. Unfortunately, I don't know much about C#, but I do have one idea. 

When you are creating a conversation, it looks like you are setting the `UniqueName` option to be equal to the room SID. I was looking at some example C# code from the [Conversation documentation](https://www.twilio.com/docs/conversations/api/conversation-resource), and it looks like the first letter of the options shouldn't be capitalized. What happens if you set these options on line 58?

```
{
  uniqueName = rooms.Sid,
  timersClosed = "P1D"
}
```

**Comment by timmydoza** [comment]
Another idea, in case the above idea doesn't work: You could go into the Twilio Console to make sure that conversations are being created with the correct uniqueName. You can start here: https://www.twilio.com/console/conversations/services. Then click on the Conversations Service that you are using (same as `_twilioSettings.ChatServiceSid`). Then, on the left click on 'Conversations', and you should see a list of conversations associated with that service. Room sids start with `RM`, so it should be easy to see if the room sid is correctly being set as the unique name. This is what it would look like in the console:

![image](https://user-images.githubusercontent.com/12685223/113746257-5abc2180-96c3-11eb-95bc-1eaf3aff63b5.png)

**Comment by Vinod1144** [comment]
Hi @timmydoza 

Thanks for reply,

Yes all is working well as mentioned, i'm sharing you the image where all _twilioSettings.ChatServiceSid is ok for both the side conversations are creating well all i need to know is where i passing the exect room sid which i have created so far from C# app, but still in screenshot you can check this.

![Untitled](https://user-images.githubusercontent.com/59162092/113753040-457add80-972b-11eb-8cc6-e0783075d426.png)

**Comment by timmydoza** [comment]
Hi @Vinod1144.

That screenshot looks good to me! I think the problem is on line 58 of TwilioService.cs. The `uniqueName` of the Conversation should be set to the room SID, but it looks like your code is setting the `UniqueName` to the room SID. The `u` in `uniqueName` should be lowercase.

What if you tried something like this?
```
        var conversation = ConversationResource.Create(
            uniqueName: rooms.Sid,
            timersClosed: "P1D"
        );
```

Can you try that out and let me know if it works?

**Comment by Vinod1144** [comment]
Hi @timmydoza 

right now i'm doing testing and i found the issue is in our react code it alwayes taking the "Default Conversatiions Service" so i have removed the extra which i have created and then i take this SID and set in my C# project and our reactJs project now it's works fine.

Thanks for you help and support.

Thanks a lot. :)

**Comment by timmydoza** [comment]
Glad to hear that it's working for you @Vinod1144! Please let me know if you have any further questions. 🙂

**Comment by 0211ms** [comment]
Hello @Vinod1144.

Can you help me in same issue which you faced like **chat conversation won't work when we have used token api of .net core**?
I have face same issue like you please check this screen short. **https://i.imgur.com/P2yzP47.png**

This is my token code. **https://imgur.com/EFSagM3**

This is my query string parameter which I send in mail and join the meeting.
https://******.com/?name=constro%20umbraco&meetingName=8520&token=**tokenvalue**

Thanks.

**Comment by 0211ms** [comment]
Hello @Vinod1144 @timmydoza 
can you please fix this asap ?

**Comment by timmydoza** [comment]
Hi @0211ms - thanks for the question!

I'm not very familiar with C# code, but I don't see any problems with the token code you shared.

Are you seeing this "There is a problem getting the conversation associated with this room" error 100% of the time, or just every once in a while?

Also, in your token server, you may need to perform additional steps before returning the token to the app. The React App will try to [connect to a conversation with a name equal to the SID of the room you are in](https://github.com/twilio/twilio-video-app-react/blob/master/src/components/ChatProvider/index.tsx#L69), so your token server will need to create this Conversation so users can join it. The JS token server that ships with this app performs the following steps:

1. [Here](https://github.com/twilio-labs/plugin-rtc/blob/master/src/serverless/functions/token.js#L65-L85), it checks to see if a Room exists with name `room_name`, and creates a room with that name if it doesn't exist.
2. [Here](https://github.com/twilio-labs/plugin-rtc/blob/master/src/serverless/functions/token.js#L65-L85), it checks to see if a Conversation exists with a name equal to the room SID from step 1, and it creates a Conversation with this name if it doesn't already exist. The conversation in this step is also [set with a one day timer](https://github.com/twilio-labs/plugin-rtc/blob/master/src/serverless/functions/token.js#L112-L128), so that the conversation is closed after one day (equal to the max length of the room). 
3. [Here](https://github.com/twilio-labs/plugin-rtc/blob/master/src/serverless/functions/token.js#L112-L128), it adds the participant identity to the conversation (ignoring any 50433 'Participant already exists' errors). 

Is your C# token server also performing these steps?

**Comment by 0211ms** [comment]
Hello @timmydoza
Thank you for your replay but my question is
I am running react video app on my server not on twilio server so I dont have a "plugin-rtc" in my local server.
So you mentioned all chanes in "plugin-rtc" react app so how I do this changes?

Thanks.
