### ISSUE TITLE
Disconnect button

### ISSUE THREAD

**Issue by Vinod1144** [twilio/twilio-video-app-react#485]
Hi @timmydoza 

I have the scenarion, i have the doctor who creates room and he is joining to the room,
now he is sharing the meeting link to it's patient, 
but now in this case after Doctor disconnect the meeting , patient still able to see the video of his own, i need to the way like if doctor disconnect the room then all participant should be disconnect from the meeting.

can you please give your ideas and view for the same.?

Thanks.

**Comment by Vinod1144** [comment]
please respond on this asap.

**Comment by Vinod1144** [comment]
?

**Comment by Vinod1144** [comment]
?

**Comment by sandeep131** [comment]
A suggestion/question - could this be done by associating a special property or flag (like 'master') in the identity of the doctor and when you get the participant disconnect event check if it is the doctor who disconnected, then you close the room?  Also working on a similar scheme to see if it will work.

**Comment by Vinod1144** [comment]
Hi @timmydoza 


1. We are using this same Video App for both end Doctor and Patient
2. Yes Doctor is the one who is going to create Room 
3. Yes Room has max 4 participant.


Please give your suggestion how we can achieve this ?

Thanks.

**Comment by timmydoza** [comment]
Hi @Vinod1144 - thanks for the additional information.

>We are using this same Video App for both end Doctor and Patient

This one might be tricky to implement since there isn't currently a way for the app to distinguish which participant is the doctor and which is the patient. One thing we could try is to have the doctor use a url with a special query parameter. So doctors would use a URL like:

`https://my-video-app-url.com?doctor=1`

And patients would use a URL like:

`https://my-video-app-url.com`

This way, the app that the doctor is using will have a way to know that it should behave differently. If we update the [App.tsx component](https://github.com/twilio/twilio-video-app-react/blob/master/src/App.tsx#L27) with the following, then I think it may work:

```diff
export default function App() {
  const roomState = useRoomState();
+
+  const { room } = useVideoContext();
+  const participants = useParticipants();
+
+  useEffect(() => {
+    const params = new URLSearchParams(window.location.search);
+    const doctor = params.get('doctor');
+
+    // If this is not the doctor's app, disconnect when there are no other participants left
+    if (doctor !== '1' && participants.length === 0) {
+      room!.disconnect();
+    }
+  }, [room, participants]);
```

(be sure to import the appropriate modules at the top of App.tsx)

Since the doctor is the one that creates the room (and presumably joins first?), then the other participants apps can be configured to disconnect if they ever find that the room is empty. This won't work, however, if any non-doctor participants join before anyone else.  This will only work if the doctor joins the room first. 

Alternatively, we can do something like @sandeep131 suggested (thanks @sandeep131!). We can append a suffix to the identity of the doctor. This can be used by the app to know which participant is the doctor. A similar approach was taken in this github issue: https://github.com/twilio/twilio-video-app-react/issues/407. Let me know if you'd rather go with this alternative approach and I can help you out there. 

Please let me know how this works out for you. Thanks!!

**Comment by timmydoza** [comment]
Closing for now. Happy to reopen this to answer more questions.
