### ISSUE TITLE
Participant types and privileges

### ISSUE THREAD

**Issue by mattrothstein** [twilio/twilio-video-app-react#523]
**Question**
Can we identify participants with special types like presenters and observers, and use this identification to restrict or grant permissions. For example: prevent participants from sharing their screen or unmuting themselves without the presenter granting it.

**Additional context**
We have adopted Twilio as our service provider for video integration but i'm unsure about how much we can do with this app or if we will need to build out our own JS app to support some of the features were hoping to have. Our use case is similar to that of a teacher to students. Where there will be a participant on the call who is the organizer and we would like to give this participant total control of what goes on in the room.

**Comment by timmydoza** [comment]
Hi @mattrothstein - thanks for the question!

This is a good question! Unfortunately, this app is built to serve a simple collaboration use case. This app doesn't have any concept of participant types, roles, or permissions. Every user is the same. Any user can share their screen, send a message in chat, or start a recording. So to answer your question, this app won't be able to accommodate a student/teacher use case out of the box.

Just for some context, this app is designed to be a few things:

- It is meant to be a reference application, so developers can look at the code to learn how to implement features in their own apps. 

- It's meant to demonstrate the various features of the Twilio Video platform. We want developers to be able to launch this app quickly to see what the Twilio Video platform offers.

- And it's meant to provide developers with a good starting point for their applications. Instead of building a video app completely from scratch, developers can get a head start by forking this app. Then, they can apply their own features and customizations to meet their use case. If you look through the apps [forks](https://github.com/twilio/twilio-video-app-react/network/members) or [network graph](https://github.com/twilio/twilio-video-app-react/network), you may come across some interesting variations on this app.

Point being, I still think that this app could be helpful to you. While you would need to modify the app to meet your use case, I think that it could give you a rather good starting position to do so. I hope that it would be easier than building an app from scratch. You could even maintain two forks of this app - one for a 'teacher' version, and one for a 'student' version. I think there's some good potential here. 

Anyway, I hope that helps! Please let me know if you have any other questions. I'm happy to help brainstorm implementation ideas, so don't be afraid to reach out.
