### ISSUE TITLE
There was a problem connecting to Twilio's conversation service.

### ISSUE THREAD

**Issue by metizror** [twilio/twilio-video-app-react#531]
While Joining the room I face this error **There was a problem connecting to Twilio's conversation service.**
![Screenshot 2021-05-28 at 4 46 20 PM](https://user-images.githubusercontent.com/8925045/119976111-4403be00-bfd4-11eb-94ab-745d93b536b7.png)

**Comment by metizror** [comment]
Can Anyone Respond to this?

**Comment by metizror** [comment]
i did from my side.

**Comment by Poufy** [comment]
> i did from my side.

Can you mention how you fixed it?

**Comment by ccanalesdote** [comment]
Could you share how you solved it? @metizror

**Comment by Mars-2030** [comment]
how did you fix this issue?

**Comment by Mars-2030** [comment]
I sent the following  but it seems not working
`# TWILIO_CONVERSATIONS_SERVICE_SID must be populated in order to use the chat feature in the app.
# Note: this variable is not required if REACT_APP_DISABLE_TWILIO_CONVERSATIONS is set to 'true'.
#TWILIO_CONVERSATIONS_SERVICE_SID=IS00000000000000000000000000000000

# Un-comment the following line to disable the Twilio Conversations functionality in the app. 
 REACT_APP_DISABLE_TWILIO_CONVERSATIONS=true`
