### ISSUE TITLE
JSON.parse: unexpected character at line 1 column 1 of the JSON data

### ISSUE THREAD

**Issue by deanbrh** [twilio/twilio-video-app-react#534]
After building a local implementation of the project and running it I receive the following error when trying to join a room. Everything works prior to clicking 'Join Now'.

I have it running on port 8081 via SSL with valid certificates.

JSON.parse: unexpected character at line 1 column 1 of the JSON data

This is using CentOS 7
npm version 6.14.13
node version 14.17.0

<img width="890" alt="image" src="https://user-images.githubusercontent.com/85302025/120669890-ca624900-c487-11eb-801c-4712f84ea067.png">

Help please?

**Comment by timmydoza** [comment]
Hi @deanbrh - thanks for the issue!

Unfortunately, I'm not sure what could be causing the problem here. If you could provide us with more information, it would increase the chance that I can help solve this.

Could you please let me know what version of the app you are using? Also what's your browser version?

Are there any errors in the browser console, or your terminal?

Lastly, could you please take a look at the request to the `/token` endpoint in the browser's devtools? I think if we look at the Response tab, we might see some clues. This is what the response tab looks like: 
![image](https://user-images.githubusercontent.com/12685223/120869847-9143da80-c554-11eb-94af-79f8df195ce4.png)

**Comment by aaalaniz** [comment]
Hey @deanbrh 

I am closing this issue. Please reopen if you are still experiencing issues.

Thanks!

**Comment by Neha-codr** [comment]
i am facing the same issue 
Plz help
![Screenshot from 2022-05-24 14-00-09](https://user-images.githubusercontent.com/69338639/169986912-dc90b334-0d52-43a9-b1ba-2339ef247151.png)

**Comment by ccali11** [comment]
> i am facing the same issue Plz help ![Screenshot from 2022-05-24 14-00-09](https://user-images.githubusercontent.com/69338639/169986912-dc90b334-0d52-43a9-b1ba-2339ef247151.png)

@NeHa-singh-NS - did you figure this one out. I was connecting to my twilio dev server just fine, but it started breaking with the same error (as your two bottom errors in your screenshot).
