### ISSUE TITLE
Identifying which participant started the meeting

### ISSUE THREAD

**Issue by Poufy** [twilio/twilio-video-app-react#545]
I am simply trying to identify which one of the participants started the meeting by trying to add an extra boolean property to the localParticipant when they first start the meeting. However, I am not sure what is the proper way to do that. I would appreciate any input.

**Comment by timmydoza** [comment]
Hi @Poufy - thanks for the question!

This is a tricky problem. Unfortunately, there isn't a way to associate metadata with a Video Room or Participant. If we could store metadata on these resources, it would make this quite easy. There's a related issue in our JS Video SDK repo: https://github.com/twilio/twilio-video.js/issues/864

If you are using our Conversations (chat) feature in this app, then we could use that to store metadata. When we create a new conversation, we can store the identity of the user who first created it as an attribute. 

In our token server, we can modify this line:
https://github.com/twilio-labs/plugin-rtc/blob/master/src/serverless/functions/token.js#L99

so that it accepts the name of the user who is creating the conversation (and room) as an attribute. 
```
          conversation = await conversationsClient.conversations.create({
            uniqueName: room.sid,
            'timers.closed': 'P1D',
            attributes: JSON.stringify({
              created_by: user_identity
            }),
          });
```

With this, we can then access these attributes inside the React Video App. We can access the conversation with the `useChatContext()` hook. For instance:

```
const { conversation } = useChatContext();
console.log('Room created by:', conversation.attributes.created_by
```

It's not a convenient solution, but we're a bit limited without the ability to store metadata on Rooms and Participants. Let me know what you think, and feel free to reach out if you have any additional questions. Thanks!

**Comment by Poufy** [comment]
Hey @timmydoza
Thanks for the reply!

Eventually what I ended up doing is adding this line to add an extra value to the localParticipant object in the useRoom.tsx connect method. Of course, using this method, the other participants will not know which one is the host, but it was good enough for my use case.

```js
(newRoom.localParticipant as any).isHost = newRoom.participants.entries().next().value === undefined;
```

However, now I came across an issue where I need other participants to see this boolean isHost when they look for the participant using this line for example

```js
  const patientParticipant = participants.find(participant => (participant as any).isHost);
```

I clearly lack information on how this application works exactly, but I see that the RemoteParticipant/Participant have fields like identity, state, tracks, ...etc, is it possible to add an extra field to those (isHost) so that other participants can see this field too?

Thank you!
