### ISSUE TITLE
Hi this application is totally in typescript I want in Javascript [react-hooks] Can anyone help me out.

### ISSUE THREAD

**Issue by rohith231** [twilio/twilio-video-app-react#546]
Hi this application is totally in typescript I want in Javascript [react-hooks]  Can anyone help me out.

**Comment by timmydoza** [comment]
Hi @rohith231 - thanks for the question!

Unfortunately, we don't have a plain JavaScript version of this repository. 

The hooks that we have in the `hooks/` directory could be used in other repositories. If you'd like to use these hooks in a JavaScript project, there are some things you can try:

##

### Use the [TypeScript Playground](https://www.typescriptlang.org/) to convert individual files. 

If you go to the playground and paste in a TypeScript file on the left, you'll see the transpiled JavaScript on the right. [Here's an example of that](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgVwM4FMCiAzb6DGMANChgMowCGM6cAvnNlBCHAORTqWFsDcAsACgh6AB6RYcACbpslZABt42ZADtCwCKtLoAEumABzABYwAFAEpEQuHHxbU8ANrGDJ4nAwx9R0wF04AF4dCmp0MwB3YFUpCAiAOmjVdCgfdzgAKjhI6NiEgDdgVGRKBQA1YHQIiRgAfnjUfFLaAB8WuABGCwsBYUFbNCxcAnNLIIA+a37bOwd4LQAldFRgAC9aYLHAyYQbGdsvNNMcmLjE1WTUt1NM7KjTgqKS8srq6DqGpoVW9q6evdsdF6ALg9zy8UoUikmHy6FUMAAMkUaJczBxlmt0GwSIsMet-tNbJwYMgoNotjsQbYwWdOCAILCYXDEci4Sk0ZwVutsXBcVz0AT9kC9nQCXtiaTtK5fPAANTsMCiPhCOhCIA) with the `useHeight` hook. You could use this to convert individual hooks over to JS, so that they can be used in another project.

##

### Convert all TS files to JS

With the following command, you can convert all TS files in this repo to JS, and save them in a separate directory. These files then can be copied to a JS project just fine. Note, this process may not preserve the original formatting and comments. 

`npx tsc --noEmit false --target esnext --outDir javascript`

That command will produce a new directory, `javascript`, which will contain the JS versions of all original source files. These files in the `javascript` directory won't be used by anything, so if you modify them, you won't see the changes reflected in the app.

Please let me know if you have any additional questions!!
