### ISSUE TITLE
Remote Video Track is Dark on iOS Safari

### ISSUE THREAD

**Issue by BorjanKalinoski** [twilio/twilio-video-app-react#558]
**Question**
Why is the remote video track dark on iOS Safari?

**Additional context**
The remote video track is displayed dark on Safari IOS (Using Safari Technology Preview) as shown in the picture below. (One way video)

I was thinking the issue is with the Browsers Autoplay Policy, but i think this should not be the case, since the audio track is played, while the video track remains dark. Also, i make sure that the user presses a "Join Call" button, to ensure user interaction, which allows the rendering of a component which runs this React useEffect.

- The HTML video element has the autoplay, muted, and playsinline properties set to true.
- The codec of the video is H264, to ensure all Safari users can join the Room (Group Room).
- After connecting to the room, I call Video.createLocalAudioTrack to acquire the local audio track, and publish the local audio track after connecting to the room. 
```
  useEffect(() => {
    const canConnectToRoom = !room && !isConnectingToRoom && token && roomName

    if (canConnectToRoom) {
      connectToRoom(token, {
        video: false,
        name: roomName,
      })
    }
  }, [room, isConnectingToRoom, token, roomName, connectToRoom])
```
![image](https://user-images.githubusercontent.com/37346995/126989423-474e0233-5133-4e54-8b7a-13bd320f0fde.png)

**Comment by olipyskoty** [comment]
Hi @BorjanKalinoski, thanks for the question! 

It is hard to say what is happening without reproducing the issue. Do you mind providing us with some more information to help us reproduce?

- Does this behavior occur in the vanilla Twilio Video React app in the version of Safari that you are using?
- Can you please provide us with your Room SIDs? We can use these to take a deeper look at your video and audio tracks.
- Finally, can you please provide your exact steps to reproduce this behavior?:

**To Reproduce**
Steps to reproduce the behavior:
  1. Go to '...'
  2. Click on '....'
  3. Scroll down to '....'
  4. See error 


Without this information, it is difficult for us to pinpoint where the issue is coming from. Let us know if you have any questions in the meantime and have a great weekend!

**Comment by BorjanKalinoski** [comment]
Hello @olipyskoty We really have no idea what the issue might be, this happens on most iOS devices (not all). It works for Desktop - Desktop, Android - Desktop, but not IOS - Desktop, any help is appreciated.
- I cannot reproduce the issue locally, neither with our app neither with Twilio Video React App
- Room SID: RMf465abad03dd1d074e61f35c2e436cb9
- To reproduce in our app (example in video):
We have two sides: employee and customer
1. The employee creates a room and joins it, while publishing his audio and video tracks (Google Chrome Browser)
2. The customer joins the created room, only publishing his audio track (one way video, two way audio) (Safari IOS 14.6)
- Tried with both VP8 video codec and H264 video codec.
- The dimensions of the published video track are 1280x720 @ 24FPS

Expected behaviour: The customer should be able to see the employees video

Actual behaviour: The customer sees the employee's video as black. (The hang out tight message is displayed when the employee disables his camera)


https://user-images.githubusercontent.com/37346995/127843727-1e3cd95d-b313-4349-97df-e6c22e995f4f.mp4

- It should not be an autoplay policy issue, since both parties join the room after a button click (audio is also working, the video has *muted autoplay playsinline* properties)
- It should not be a codec issue, since we reproduced this issue with both possible codecs

**Comment by BorjanKalinoski** [comment]
One thing i just noticed is that when i run the twilio [network-tests](https://networktest.twilio.com) on Safari Technology Preview I get these issues:
![image](https://user-images.githubusercontent.com/37346995/127851440-445f391d-a098-4ed9-b975-8cafe9826e66.png)
These tests passed on Google Chrome and on the iOS browser we did the testing in the question above

**Comment by BorjanKalinoski** [comment]
Here are room SIDs where the issue occurred:

RM6341295fd6d46b3f04cb0cdc8e9a3f2f
RMf955e2a3136909929047da887d7fbe2c
RM6de41d9058caa1e3ab3da5ff222b6280
RMf465abad03dd1d074e61f35c2e436cb9

Here are room SIDs tested with iOS devices where it was working:

RMaa0e9000068336c496c1ed2e682d086d
RM8d3cd0e432fde16c8e9764ba37bfd89c
RM855fd6a27ed4d83f68fc007a8916c219

**Comment by BorjanKalinoski** [comment]
@olipyskoty I managed to reproduce this bug on Twilio Video App React

**To reproduce**
1. Change the Room Settings Video Codec from Twilio Console to H264
2. Create a room and make sure one of the participant joins from Safari Technology Preview browser

**Expected result** :  The participant using Safari Technology Preview should see the video of the other participant (which uses chrome or any other browser)

**Actual result**:  The participant using Safari Technology Preview sees a black box instead of  the remote video

![image](https://user-images.githubusercontent.com/37346995/128200704-65041b03-637c-45e2-b1f7-973681991f31.png)

**Comment by olipyskoty** [comment]
Hey @BorjanKalinoski, thanks so much for providing the steps to reproduce! We will be looking into this today. 

Could you please provide the specific version of Safari Technology Preview that you are using? 

Also, are you able to reproduce this in iOS Safari? If so, which version are you using?

Thank you!

**Comment by BorjanKalinoski** [comment]
@olipyskoty 

These are the devices we have tested so far on our application (not twilio-video-react-app), but the issue seems similar, and the code is mostly based on your app structure. My guesses are either the phone model, autoplay problems, or the way video track is being rendered. It seems to me that there is no no correlation with the iOS version, but Im really curious if you can reproduce this at your end.

![image](https://user-images.githubusercontent.com/37346995/128229069-6eaf86e1-8632-43c6-b435-2604ab24fae3.png)

Safari Technology Preview version: Release 128 (Safari 15.0, WebKit 16612.1.22.11.3)

**Comment by olipyskoty** [comment]
Hi @BorjanKalinoski! 

We did some testing on our end and were able to reproduce the issue with the twilio-video-react-app using Safari Technology Preview and the video codec set to `H.264`. That being said, all of our [supported browsers](https://www.twilio.com/docs/video/javascript#supported-browsers) seem to be working as expected, so we do not suspect this issue is coming from the app. 

We currently do not test for, or use, the Safari Technology Preview browser, so it is hard to say where the issue might be coming from. However, regular Safari and iOS Safari have both been thoroughly tested, and are supported by this app. I did notice that the [twilio-video sdk](https://github.com/twilio/twilio-video.js) still returns true for `Video.isSupported` for Safari Technology Preview, so I have filed an internal ticket to ensure it returns false. 

Oddly enough, I was able to get this app to work using Safari Technology Preview by setting the video codec to `VP8` or `VP8 & H.264`. But we can't be sure as to why that is due to our lack of familiarity with the browser.

We are sorry that we could not be of more help to you and we hope that you find a solution soon. Please let us know if you have any other questions and have a great weekend! 🎉

**Comment by BorjanKalinoski** [comment]
@olipyskoty Thank you for your assistance. We finally figured out what the issue was, the function that we used to join a video room was asynchronous, and i read somewhere that it interacted with the user interactivity index , which caused the video to be blocked 🤦 So we made that function synchronous. And we rendered the Participants and their tracks based on the room state (connected, disconnected), where before we were using a local state variable to do this.

Another issue that we are having, and we managed to reproduce it on twilio-video-app-react (both iOS and STP), is that the remote audio is blocked when local microphone access is denied. We fixed this to not let the users join a room if they haven't allowed their microphone (not ideal, but it works). It will rarely happen, but you never know what the users will do. 

Let me know if you will tackle this issue anytime.

Thank you again, enjoy the rest of the week!

**Comment by olipyskoty** [comment]
Hey @BorjanKalinoski that's great to hear! Glad you figured it out 🎉

We tried to reproduce the second issue with the information that you have provided and were unable to do so. If you continue to see this behavior, please open up a new issue ticket with the exact steps on how to reproduce. 

Thanks again!
