### ISSUE TITLE
Switch camera is not working in some of the devices

### ISSUE THREAD

**Issue by jitesh-prajapati123** [twilio/twilio-video-app-react#566]
Switch camera is not working in some of the devices.

**Comment by timmydoza** [comment]
Hi @jitesh-prajapati123 - thanks for the issue. 

Sorry to hear that the Switch Camera feature may not be working properly. Unfortunately, this issue doesn't contain enough information for us to identify and fix the problem. We'll need to know more information in order to look into this. 

Can you please create a new issue and use the "Bug Report" template? It has many questions in it that you can answer which will give us the information that we need.  Just click on the "Get Started" button for the "Bug Report" label:
![image](https://user-images.githubusercontent.com/12685223/129620097-3c7bfd12-6b8e-4bc4-a48e-cec5a81b7981.png)

Thanks!
