### ISSUE TITLE
Warn users when closing tab with ongoing meeting

### ISSUE THREAD

**Issue by jszem** [twilio/twilio-video-app-react#567]
**What is the feature that you would like to see in the app? Please describe.**
As a meeting participant, I want to receive a warning when I try to close a tab with an active meeting in it so that I am stopped from accidentally closing the meeting

**Is your feature request related to a problem? Please describe.**
Errant clicks that result in kicking users out of an active meeting, particularly those that require log ins to access, greatly increases user frustration

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by olipyskoty** [comment]
Hi @jszem thank you for the feature request!

We agree that this feature would be a great addition to the app, however we tested it out and due to browser limitations, we decided to forgo including this functionality in the twilio-video-app-react. That being said, we are happy to share what we tried with you so that you can try it out and decide if it is worth adding this feature to your own app:

Replace [lines 54-55](https://github.com/twilio/twilio-video-app-react/blob/fe6c693dfe3d0c5d08a1d0f6b899b6f44416defd/src/components/VideoProvider/useRoom/useRoom.tsx#L54) in `useRoom.tsx` with the following:

```
          function handleBeforeUnload(e: any) {
            e.preventDefault();
            e.returnValue = '';
          }

          window.addEventListener('beforeunload', handleBeforeUnload);
          
          // Add a listener to disconnect from the room when a user closes their browser
          window.addEventListener('unload', disconnect);
```

**Limitations:**
 As mentioned above, this change does come with some interesting behavior:

- The "prompt" or "warning" does not have the ability to display custom messages. For instance, Chrome's message will always be `Do you want to leave this site? Changes you made may not be saved.`. More info can be found [here](https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onbeforeunload#:~:text=Starting%20with%20Firefox%2044%2C%20Chrome%2051%2C%20Opera%2038%2C%20and%20Safari%209.1%2C%20a%20generic%20string%20not%20under%20the%20control%20of%20the%20webpage%20will%20be%20shown%20instead%20of%20the%20returned%20string.%20For%20example%3A).
- When the warning is displayed, the JavaScript thread is stopped. We tested this by running `setInterval(() => console.log(Date.now()), 1000)` in the Chrome console and noticed that `Date.now()` stops being logged as soon as the dialog shows up.
- The warning stops the signaling connection process which is needed for one video participant to be connected to another video participant. The participant with the "close tab warning" will actually disconnect from the video room, but they won't know that they have been disconnected until they hit the "Cancel" button on the prompt. 
- Finally, it is possible that the `unload` event is less reliable than the `beforeunload` event (see more [here](https://developers.google.com/web/updates/2018/07/page-lifecycle-api#legacy-lifecycle-apis-to-avoid)), so it might be best to avoid using the `unload` event at all.

We're sorry that we could not implement this feature into the twilio-video-app-react. Feel free to try out this code out in your own app and let us know if you have any other questions!
