### ISSUE TITLE
Android Video feed is not working.

### ISSUE THREAD

**Issue by vikashbhut** [twilio/twilio-video-app-react#577]
Expected behaviour
On video call connect the video feed should run on both the web and android devices.

Actual behaviour
On Video call connect the android video feed is not working. Neither front or back camera is giving feed , but both the camera are reflecting in the local video. Voice is properly functional but video is not being sent.

Solution:-

`{(!isVideoEnabled || isVideoSwitchedOff) && (
        <div className={classes.avatarContainer}>
          <AvatarIcon />
        </div>
      )}`

After commenting this code in MainParticipantInfo.tsx everything is working fine.
It looks that there is an issue with isVideoEnabled Flag.
Even if video data is coming from Android phone, this flag returns false and due to that it overwrites with AvatarIcon View.
In iOS, it’s working as expected.

**Comment by timmydoza** [comment]
Hi @vikashbhut - thanks for the issue!

I just tried using this app on desktop Chrome and Android Chrome, and everything worked as expected. I'm not able to reproduce the issue you describe. 

Can you please share more information about the issue? The more information you can provide, the better chance we'll have of identifying the issue.

What version of twilio-video-app-react are you running?
What kind of android device and OS are you running twilio-video-app-react on?
What browser and browser version are you using?
What are the specific steps that you are taking to reproduce the issue?

I see that this issue was referenced from a react-native repo. Are you running this app (twilio-video-app-react) on Android, or are you running a different app? 

Thanks for the extra info!

**Comment by vikashbhut** [comment]
I found solution in twilio-video-react-app inside  MainParticipantInfo.tsx  need to update  const videoPublication = publications.find(p => p.trackName.includes('camera')); to  const videoPublication = publications.find(p => p.trackName === 'camera' || p.kind === 'video'); .

**Comment by vikashbhut** [comment]
> Hi @vikashbhut - thanks for the issue!
> 
> I just tried using this app on desktop Chrome and Android Chrome, and everything worked as expected. I'm not able to reproduce the issue you describe.
> 
> Can you please share more information about the issue? The more information you can provide, the better chance we'll have of identifying the issue.
> 
> What version of twilio-video-app-react are you running?
> What kind of android device and OS are you running twilio-video-app-react on?
> What browser and browser version are you using?
> What are the specific steps that you are taking to reproduce the issue?
> 
> I see that this issue was referenced from a react-native repo. Are you running this app (twilio-video-app-react) on Android, or are you running a different app?
> 
> Thanks for the extra info!

I am using react-native android app and react web app. for web app i am using   "twilio": "^3.57.0", "twilio-video": "^2.14.0" and in react-native using react-native-twilio-video-webrtc

**Comment by timmydoza** [comment]
Hi @vikashbhut!

In out most recent release, we included a change that may fix this problem. This video app used to only display a participant's video if their video track was published with the name `camera`. This meant that if a user join a room from another app, that their video won't be displayed if the other app didn't include a track name of `camera`. This requirement removes this restriction, and now any video track will be displayed, regardless of name. 

I think this may fix your issue. Would you mind trying your Android app with the most recent version of this React video app? I hope that it solves your problem. Please let me know how it works out for you!

**Comment by vikashbhut** [comment]
> Hi @vikashbhut!
> 
> In out most recent release, we included a change that may fix this problem. This video app used to only display a participant's video if their video track was published with the name `camera`. This meant that if a user join a room from another app, that their video won't be displayed if the other app didn't include a track name of `camera`. This requirement removes this restriction, and now any video track will be displayed, regardless of name.
> 
> I think this may fix your issue. Would you mind trying your Android app with the most recent version of this React video app? I hope that it solves your problem. Please let me know how it works out for you!

Currently , I have changed  const videoPublication = publications.find(p => p.trackName.includes('camera')); with const videoPublication = publications.find(p => p.trackName === 'camera' || p.kind === 'video'); and everything is working fine now.from android side getting kind === 'video' ;

**Comment by epalacio90** [comment]
i have the same issue, it replicates when i use Android app developed with this library https://github.com/blackuy/react-native-twilio-video-webrtc 

The solution proposed by @vikashbhut worked for me.

**Comment by timmydoza** [comment]
Sounds good everyone! Looks like you found a solution. 

I think that the newest version of this app will also work, because we made a similar change that is like the code you shared. Now, the app does not look for the name of `camera` when it renders remote video tracks. This should improve the interoperability of this app with other third party solutions. 

Please let mw know if there's anything outstanding and I'll be happy to reopen the issue. Thanks!

**Comment by chismadalina** [comment]
@epalacio90 what was the fix for https://github.com/blackuy/react-native-twilio-video-webrtc exactly?
