### ISSUE TITLE
How to implement one to one chat feature?

### ISSUE THREAD

**Issue by SanjayBikhchandani** [twilio/twilio-video-app-react#624]
@timmydoza Can we use Twilio conversation API for this?

**Comment by timmydoza** [comment]
Hi @SanjayBikhchandani - thanks for the question! I think it would be possible to do this with the conversations API. It would be much more complicated than the current implementation though. 

Right now, every time a room is created, this app's backend will created a new [conversation resource](https://www.twilio.com/docs/conversations/api/conversation-resource) associated with the room. This 'conversation resource' is where all of the group chats in the room happen. 

So in order to have a one to one video chat, this app's backend would have to create a new conversation resource for every 1:1 conversation that happened in the room. This could be quite a lot of conversations, but I think it would still be possible to implement with some work. Unfortunately, this feature is a bit out-of-scope for this video app, so we won't be implementing it. 

Thanks again for the question! Please let me know if there's anything else we can help with.
