### ISSUE TITLE
Equal size video tracks - possible?

### ISSUE THREAD

**Issue by baj84** [twilio/twilio-video-app-react#627]
Hi,

My question relates to #191 

It's a requirement for my customers to have equal size video tracks, since my application is used for online therapy sessions.

I understand it's not on the roadmap, so i'm curious to find out if it is technically possible to do with the current architecture and if so, could someone point me in the right direction to start implementing it myself?

![80960523-54fdf200-8e09-11ea-9de6-16715bd5e331](https://user-images.githubusercontent.com/2744292/150239001-740a89f0-914b-43fb-8278-99f88e0dd3af.png)

Any feedback is appreciated.

Thanks

**Comment by yashrojesara** [comment]
@baj84 It's definitely possible.

you just need to create another component in which you can render equal size of videos tracks by adding CSS based on the participants length which you can get from **useParticipants** hook.

**Comment by timmydoza** [comment]
Hi @baj84 - thanks for the question! 

I think it's definitely possible. One good resource to take a look at is this demo: https://github.com/Alicunde/Videoconference-Dish-CSS-JS

Here's the live demo: https://alicunde.github.io/Videoconference-Dish-CSS-JS/

It's a nice implementation of a grid view for video. I'll be sure to update this ticket if we ever add anything like this to the app. We know it's something that our customers want 🙂.

One thing to note about my [previous comment here](https://github.com/twilio/twilio-video-app-react/issues/191#issuecomment-645738210), is that it is now possible to switch between a grid view and a collaboration view without having to worry about the bandwidth profiles. This is possible due to the recent introduction of [adaptive simulcast](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md#2190-january-31-2022) in the twilio-video SDK. The twilio-video will now automatically request the most appropriately sized simulcast layer based on the size of the rendered video element in your application. This means that the application can change the size of the video tiles between a grid view and collaboration view and the bandwidth usage will be adjusted automatically. 

Thanks for the question and please let me know if there's anything else we can help with!
