### ISSUE TITLE
Regarding video recording stop.

### ISSUE THREAD

**Issue by 0211ms** [twilio/twilio-video-app-react#630]
Hello,
Please guide me for this error.
https://i.imgur.com/M5R1wcM.png

I have a create a room with auto join recording while I am click on stop recording button I will face error like above image so please guide me for this.

Thanks.

**Comment by 0211ms** [comment]
Hello,
Please revert on priority base. Its little bit urgent.

**Comment by olipyskoty** [comment]
Hi @0211ms thanks for reaching out!

Unfortunately, I am unable to reproduce the issue, but based off of your screenshot, it appears that your app is trying to hit a `//recordingrules` endpoint. That extra slash `/` might be the culprit. Try removing that extra slash and let us know if that works for you!

If you are still having trouble, we will need some more information in order to try and reproduce the issue:

- Could you please explain how you are enabling the auto-record feature? One simple way is by updating your Room settings via the [Twilio Console](https://console.twilio.com/). Once logged in, navigate to Develop > Video > Manage > Room Settings. Scroll down to the Recording section and set the `Participants will be recorded on connect` setting to **Enabled**. Click **Save** at the bottom.
- What does your environment look like? Please provide the following:

>  - OS: [e.g. Ubuntu 18.04]
>  - Browser: [e.g. Chrome 80, Firefox 72]
>  - App Version: [e.g. 0.1.0]
>  - SDK Version: [e.g 2.1.0]
>  - Node.js version: [e.g. 12.14.1]
- A Room SID where you have experienced this error

Hopefully our first suggestion works for you, but please let us know if you have any other questions. Thank you!
