### ISSUE TITLE
Video Toggle Button on Permission Denied

### ISSUE THREAD

**Issue by adyaksaw** [twilio/twilio-video-app-react#640]
**Question**
Hello, I have a question regarding the video toggle button. I see that to decide whether the video is enabled or not, it uses `enumerateDevices()`. https://github.com/twilio/twilio-video-app-react/blob/923fa2c799b39fc6191c5ea0892c2f448b59a5ab/src/components/Buttons/ToggleVideoButton/ToggleVideoButton.tsx#L13

But this behavior is different for the audio button, where it uses `localTracks()` directly from `VideoContext`.

https://github.com/twilio/twilio-video-app-react/blob/923fa2c799b39fc6191c5ea0892c2f448b59a5ab/src/components/Buttons/ToggleAudioButton/ToggleAudioButton.tsx#L13

When I tested and disabled the permission, I found out that the Audio button is disabled, while the Video button is not. Is this intended?

![image](https://user-images.githubusercontent.com/12467497/153563997-4c7c8c2e-1ee4-44d3-b5c0-f82647c479ac.png)

**Additional context**
I further found out that when calling `enumerateDevices()` when the permission is blocked, it will return an empty `deviceId`. That's why the button is enabled. The reasons for that can be found in the following StackOverflow question.

https://stackoverflow.com/questions/65356567/webrtc-mediadevices-enumeratedevices-returns-empty-deviceid

**Comment by olipyskoty** [comment]
Hey @adyaksaw, great question!

This was intentional. We wanted to ensure that users without a camera are able to use the app, so we ask for microphone and camera access separately.
![Screen Shot 2022-02-14 at 3 14 20 PM](https://user-images.githubusercontent.com/77076398/153968776-4716e553-9ed3-41c3-81d8-ce7776b71428.png)

The Start Video button will be disabled when a user does not have a camera (we determine this by `hasVideoInputDevices: devices.some(device => device.kind === 'videoinput')`). Note that if a user does not have a camera, there will not be a `videoinput` when calling `enumerateDevices()`. However, this will be true if the user denies -or grants- permission (but like you said `deviceId` will be empty if denied). 

Interestingly, `localTracks.some(track => track.kind === 'video')` returns false whether the user does not have a camera, explicitly denies the browser permission to use it, and even when the user granted permission but switched their camera off. This is also why we didn't use the same logic as the `ToggleAudioButton`. We wanted to make sure that we didn't erroneously disable this button if the user decided to switch off their camera.

When a user does not have a microphone, or explicitly denies the browser permission to use it, `localTracks.some(track => track.kind === 'audio')` is false. However, if they grant the browser permission and then later turn off their microphone, `localTracks.some(track => track.kind === 'audio')` is true (but `track.isTrackEnabled` is `false`).

Hope that answers your question, but let us know if you need further clarification or have any other questions!

Thank you!

**Comment by adyaksaw** [comment]
@olipyskoty  I see, that's a weird behavior. Is there any way to make the `Start Video` button be disabled like the audio one only if the permission is disabled? Because in the current state, if I click the `Start Video` while previously I denied the permission, it will show an error.
