### ISSUE TITLE
It isn't able to find the profile on deploy

### ISSUE THREAD

**Issue by Zeusakos** [twilio/twilio-video-app-react#641]
i followed everything at your readme but i keep getting 

» Could not find profile.
 » To create the profile, run:

  twilio profiles:create

Alternatively, twilio-cli can use credentials stored in environment variables:

# OPTION 1 (recommended)
export TWILIO_ACCOUNT_SID=your Account SID from twil.io/console
export TWILIO_API_KEY=an API Key created at twil.io/get-api-key
export TWILIO_API_SECRET=the secret for the API Key

# OPTION 2
export TWILIO_ACCOUNT_SID=your Account SID from twil.io/console
export TWILIO_AUTH_TOKEN=your Auth Token from twil.io/console

i have set the right user active, in the user list in terminal displays everything but on deploy not.
Then i tried the options above but still nothing

**Comment by olipyskoty** [comment]
Hi @Zeusakos, thanks for reaching out!

Sorry for the inconvenience 😅 . We had to make some updates to the [rtc plugin](https://github.com/twilio-labs/plugin-rtc) so that it is compatible with version 3.x of the twilio-cli.

Please run the following terminal command to upgrade the plugin:
```
twilio plugins:update
```

You should now be able to follow the deployment steps in the `README.md` without issue. Please let us know if you have any questions, or run into any issues.

Have a good weekend!
