### ISSUE TITLE
about passcode

### ISSUE THREAD

**Issue by Zeusakos** [twilio/twilio-video-app-react#645]
Is it possible to make the passcode not expire after a week? Or any way to deploy this specific project to twilio without expiring?

**Comment by olipyskoty** [comment]
Hey @Zeusakos thanks for the question! 

Unfortunately, we don't have a feature in our CLI plugin that allows you to change the passcode expiration date. We decided to set it to one week for security reasons (the numeric passcode is weak and could be guessed). Also, the quick deploy feature is only meant to be used for demo purposes.

That said, if you do want to change the expiration date (which we don't advise), that can easily be accomplished.

Our CLI plugin prints a link to the Functions editor in the Twilio Console. To obtain this URL, either deploy a new app or run ` twilio rtc:apps:video:view` in your terminal.  With this editor, you can edit the live token server and change environment variables. Please visit the printed URL and  click on Settings > Environment Variables. Then you can edit the API_PASSCODE_EXPIRY variable, like this:

![image](https://user-images.githubusercontent.com/77076398/154571119-894a1b21-b650-4059-8151-371ee2f40577.png)

The API_PASSCODE_EXPIRY is the time that the passcode will expire, represented as the number of milliseconds that have passed since 1-1-1970. Simply change this number to whatever value you want.

Please check out this past issue for more information: #342, and let us know if you have any questions. Thank you!
