### ISSUE TITLE
iOS 15 Safari remote audio minimal/soft at max volume

### ISSUE THREAD

**Issue by matstc** [twilio/twilio-video-app-react#650]
**Describe the bug**
I'm creating this issue to track [this downstream bug](https://github.com/twilio/twilio-video.js/issues/1586) in twilio-video.js. That bug seems to be the cause of quiet audio for many users of our app. I suspect this bug affects most apps using twilio-video-app-react.

**To Reproduce**
See link above.

**Additional context**
There's [a workaround](https://bugs.webkit.org/show_bug.cgi?id=230902#c18) mentioned but it requires access to the remote audio stream. I can only find a way to get access to the tracks.

I'd be grateful if someone could advise on how to implement this workaround in this codebase, or on how to get access to the remote audio stream.

Thanks!

**Comment by timmydoza** [comment]
Hey @matstc - great question!

Getting the the MediaStream for an audio track can be a little complicated, but it's definitely possible. In fact, we [already do it](https://github.com/twilio/twilio-video-app-react/blob/master/src/components/AudioLevelIndicator/AudioLevelIndicator.tsx#L30-L37) in the [AudioLevelIndicator.tsx component](https://github.com/twilio/twilio-video-app-react/blob/master/src/components/AudioLevelIndicator/AudioLevelIndicator.tsx).

What's tricky, is that we can't just access the track's MediaStream. Instead, we need to access the track's [MediaStreamTrack](https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamTrack), and use that to create a [MediaStream object](https://developer.mozilla.org/en-US/docs/Web/API/MediaStream). What's even trickier, is that the twilio-video SDK may restart the MediaStreamTrack at any time (most likely on mobile Safari), so we need to watch out for that, but the [useMediaStreamTrack.ts hook](https://github.com/twilio/twilio-video-app-react/blob/master/src/hooks/useMediaStreamTrack/useMediaStreamTrack.ts) already accounts for this. 

Anyway, lots of these things are already taken into account in that [AudioLevelIndicator.tsx component](https://github.com/twilio/twilio-video-app-react/blob/master/src/components/AudioLevelIndicator/AudioLevelIndicator.tsx), so I think that would be a great place to implement the workaround. Every participant in the room will already have an AudioLevelIndicator displayed on top of their video. Try adding the workaround code inside of the [initializeAnalyser function](https://github.com/twilio/twilio-video-app-react/blob/master/src/components/AudioLevelIndicator/AudioLevelIndicator.tsx#L14-L24). I think this would be a convenient place to add it, since the AudioContext and MediaStream objects are already available. The [AudioLevelIndicator.tsx component](https://github.com/twilio/twilio-video-app-react/blob/master/src/components/AudioLevelIndicator/AudioLevelIndicator.tsx) component will automatically take care of the weird edge cases regarding mobile devices, and the restarting of MediaStreamTracks. 

Looks like this issue has been fixed in iOS 15.4.0, which should hopefully be rolled out soon. In the meantime, please let me know how this workaround works for you, and if you have any other questions. I'll leave this issue open until we see a fix rolled out in iOS Safari. 

Thanks!

**Comment by matstc** [comment]
Hi @timmydoza. Thanks a lot for the detailed response, that's very helpful.

The priorities have shifted a bit on our end so the new iOS release might or might not beat me to it. I'll come back here with details if I end up with a good workaround.

Thanks.

**Comment by timmydoza** [comment]
Looks like this has been fixed in iOS 15.4! Please let me know if you have any other questions.
