### ISSUE TITLE
Changing video layouts

### ISSUE THREAD

**Issue by pavsidhu** [twilio/twilio-video-app-react#658]
**Question**
I noticed that this reference app doesn't have an example of the participant layout changing, for example from a spotlight view (as is at the moment) to a grid view. Is there any reason why this would break?

I tested an example where I mount a Participant component, unmounted it and remounted it elsewhere and there was a brief flash before the track was added to the video element. Is there something I could do to avoid this? Thanks!

**Comment by timmydoza** [comment]
Hi @pavsidhu - thanks for the question!

I think that the brief flash that you might be seeing has to do with a relatively new Twilio-Video SDK feature call Automatic Track Switch Off. More information about the feature can be found in [this part](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md#2140-may-11-2021) of the twilio-video changelog. 

When this feature is enabled, which it is in this app (and by default), the SDK will automatically determine when the `<video>` element for a given track is visible, and if it is not visible (because the element is off the page), then it will 'shut off' the track. When the track is shut off, your browser will stop receiving data for that track, and it will free up some bandwidth and cpu consumption. It's a great feature to automatically enhance the performance of a video application. 

This feature even works when you switch tabs away from the video app. The SDK will detect that the video app is no longer the visible tab, and it will switch off all the video tracks. When you switch back to the video app tab, you might see a brief flicker before video starts flowing again. This is because it can take a brief moment before the track is switched on again.

It's important to note, that in this app - when a video track is switched off, you will see an avatar icon, like this:

<img width="264" alt="image" src="https://user-images.githubusercontent.com/12685223/159585947-bcaa1f1d-7b91-4a96-8afc-8962c9a50597.png">

We show this icon because a track can be switched off for other reasons - not just when it isn't visible on a page. For instance, if your network is slow or has limited bandwidth, then the SDK will selectively switch off tracks so that it can still receive data for the higher priority tracks (like the dominant speaker's video track). If we didn't show this avatar when a track is switched off due to low bandwidth, then the last frame of the participants video will be shown and the video will look frozen, which is not a good experience for users. 

So I suspect that if this feature is turned off (which would consume more resources, but that might be just fine depending on your use case), then the video tracks will never be switched off by the SDK, and then you shouldn't see the flicker. This can be done by setting `clientTrackSwitchOffControl: 'manual'` in the Video SDK's connect options. 

Please let me know if this solves the issue for you, or if you have any other questions. Thanks again for reaching out!
