### ISSUE TITLE
How do I add a background to my video calls?

### ISSUE THREAD

**Issue by SharonGilmore** [twilio/twilio-video-app-react#689]
**Question**
I have a React app which uses the twilio-video library to allow users to make a video call.  This bit is working fine.

Now I want to add a custom background to the call.  I've installed the twilio-video-processors package and followed the tutorial which uses it to add a custom background in an express app, and that works.  However, when I try to transfer this to my React app, I'm getting an error when it tries to load the background image.

I have the following code:
```
let img = new Image();
  img.src = 'mainImg.jpg';
  img.onload = async () => {
    try {
      const bg = new VirtualBackgroundProcessor({
        assetsPath: '/',
        backgroundImage: img,
      });
      await bg.loadModel();
    } catch (error) {
      console.log('Error: ', error);
    }
}
```
I have `mainImg.jpg` in my public folder, and can navigate to it using localhost:3000/mainImg.jpg.

If I do console.log(bg) just before attempting bg.loadModal(), the virtual background has the correct src.

When I try to run this, I get the following error when it gets to bg.loadModal():

```
RuntimeError: abort(CompileError: WebAssembly.instantiate(): expected magic word 00 61 73 6d, found 3c 21 64 6f @+0). Build with -s ASSERTIONS=1 for more info.
    at abort (tflite-1-0-0.js:354:15)
    at tflite-1-0-0.js:445:13
```
I'm running the app with 'npm start', but I've also tried building a static version and running that - I'm not sure whether I need to do that or not, but it doesn't seem to help.

For the assets path, I've tried process.env.PUBLIC_URL instead of '/', which again didn't help.

Can you help me out with what to try next?  Thank you for any help you can give!

**Versions**
I'm developing on MacOS, and running the app on Chrome.
React version: 17.0.2
twilio.js: 3.77.1
twilio-video.js: 2.15.1
@twilio-labs/plugin-rtc: ^0.8.2,
"@twilio/conversations: ^1.2.3,
"@twilio/video-processors: ^1.0.0,

**Comment by yashrojesara** [comment]
@SharonGilmore You need to put this [Assets](https://github.com/twilio/twilio-video-processors.js/tree/master/assets) in the public folder and then need to give reference in your code in `assetPath`

**Comment by olipyskoty** [comment]
Sorry for the delayed response. Thanks for the help @yashrojesara!

Are you still running into this issue @SharonGilmore? If so, @yashrojesara is correct. You will need those files in your public folder in order to get the virtual background functionality to work properly. Please see the Twilio Video Processors [README](https://github.com/twilio/twilio-video-processors.js#assets) for more information.

You can also copy the files from the `build` folder by navigating to `node_modules` > `@twilio` > `video-processors` > `dist` > `build`. Then add those files to your `/public` directory, which should then allow you to use `'/'` for your `assetsPath`. In this app we created a `virtualbackground` folder containing those files under `/public`, so our `assetsPath` is `'/virtualbackground'` (see [here](https://github.com/twilio/twilio-video-app-react/blob/6e481aa95247b8d63391011f67b4797a910efed6/src/components/VideoProvider/useBackgroundSettings/useBackgroundSettings.ts#L129)).

Hopefully this helps, but let us know if you have any other questions and we will reopen this issue! Thanks!
