### ISSUE TITLE
How to change room type without recreating room with Programmable Video SDK

### ISSUE THREAD

**Issue by dttrinh** [twilio/twilio-video-app-react#702]
I have a scenario below:
I have created a Go Room with Programmable Video SDK and have 2 participants joined this room.
Then I want to invite one more user to participate in this room, so I need another room with room type P2P or Group Room (because Go Room just allows max 2 participants).
The question is can I update the existing Go Room to P2P or Group Room without deleting the old room and creating a new one with desired room type.
Because it will affect users' experiences and maybe lose all of the existing room info including room chat message history.
I have checked the API docs but didn't find the Room Update API.
https://www.twilio.com/docs/video/api/rooms-resource

Thank you and regards.

**Comment by timmydoza** [comment]
Hi @dttrinh - thanks for the question!

Unfortunately, there is no way to change a room type while a room is in progress. As you found, you'll have to create a new room with a new room type. 

This can cause an interruption, but it may be possible to do this in a way where the chat message history is preserved. Instead of using the Room SID to identify a Twilio Conversation, you could use a different identifier that is the same for the old room and the new room. Just an idea!

Thanks for the question - and please let us know if there's anything else!
